** HEADER -----------------------------------------------------
**  DO-FILE METADATA
    //  algorithm name          1_prep_deaths.do
    //  project:                BNR
    //  analysts:               Jacqueline CAMPBELL
    //  date first created      03-SEP-2019
    // 	date last modified      03-SEP-2019
    //  algorithm task          Prep and format death data
    //  status                  Completed
    //  objectve                To have one dataset with cleaned 2018 death data.
    //  note 1                  Duplicate 2017 deaths checked using 2018 dataset against 2008-2017 dataset 
    //                          (see '2017 deaths_combined_20190828.xlsx')
    //  note 2                  Duplicates within 2018 deaths checked and identified using conditioinal formatting and 
    //                          field 'namematch' in 2018 dataset (see 'BNRDeathData2018_DATA_2019-08-28_1101_excel.xlsx')
    //  note 3                  Cleaned 2018 dataset to be merged with 2008-2017 death dataset; 
    //                          Redcap database with ALL cleaned deaths to be created.

    
    ** General algorithm set-up
    version 15
    clear all
    macro drop _all
    set more off

    ** Initialising the STATA log and allow automatic page scrolling
    capture {
            program drop _all
    	drop _all
    	log close
    	}

    ** Set working directories: this is for DATASET and LOGFILE import and export
    ** DATASETS to encrypted SharePoint folder
    local datapath "X:/The University of the West Indies/DataGroup - repo_data/data_p141"
    ** LOGFILES to unencrypted OneDrive folder (.gitignore set to IGNORE log files on PUSH to GitHub)
    local logpath X:/OneDrive - The University of the West Indies/repo_datagroup/repo_p141

    ** Close any open log file and open a new log file
    capture log close
    log using "`logpath'\1_prep_deaths.smcl", replace
** HEADER -----------------------------------------------------

********************
** DATA PREPARATION  
********************
use "`datapath'\version01\2-working\2018_deaths_imported_dp"


*******************
** DATA FORMATTING  
*******************
** PREPARE each variable according to the format and order in which they appear in DeathData REDCap database
/*
(1) record_id (auto-generated by REDCap): Created for import
(2)  cfdate: 		Y-M-D H:M
(3)  cfda: 			REDCap username, reg.dept., intern
(4)  certtype:		1=MEDICAL 2=POST MORTEM 3=CORONER 99=ND
(5)  regnum:		Integer - min=0001, max=9999
(6)  district:		1=A 2=B 3=C 4=D 5=E 6=F
(7)  pname:			Text, if missing=99
(8)  address:		Text, if missing=99
(9)  parish:		1=Christ Church 2=St Andrew 3=St George 4=St James 5=St John 6=St Joseph 7=St Lucy 8=St Michael 9=St Peter 10=St Philip 11=St Thomas 99=ND
(10) sex:			1=Male 2=Female 99=ND
(11) age:			Integer - min=0, max=999
(12) nrnnd:			1=Yes 2=No
(13) nrn:			dob-####, partial missing=dob-9999, if missing=.
(14) mstatus:		1=Single 2=Married 3=Separated/Divorced 4=Widowed/Widow/Widower 9=ND
(15) occu:			Text, if missing=99
(16) durationnum: 	Integer - min=0, max=99, if missing=99
(17) durationtxt:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(18) dod:			Y-M-D
(19) deathyear:		Integer
(20) cod1a:			Text, if missing=99
(21) onsetnumcod1a:	Integer - min=0, max=99, if missing=99
(22) onsettxtcod1a:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(23) cod1b:			Text, if missing=99
(24) onsetnumcod1b:	Integer - min=0, max=99, if missing=99
(25) onsettxtcod1b:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(26) cod1c:			Text, if missing=99
(27) onsetnumcod1c:	Integer - min=0, max=99, if missing=99
(28) onsettxtcod1c:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(29) cod1d:			Text, if missing=99
(30) onsetnumcod1d:	Integer - min=0, max=99, if missing=99
(31) onsettxtcod1d:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(32) cod2a:			Text, if missing=99
(33) onsetnumcod2a:	Integer - min=0, max=99, if missing=99
(34) onsettxtcod2a:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(35) cod2b:			Text, if missing=99
(36) onsetnumcod2b:	Integer - min=0, max=99, if missing=99
(37) onsettxtcod2b:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(38) pod:			Text, if missing=99
(39) deathparish:	1=Christ Church 2=St Andrew 3=St George 4=St James 5=St John 6=St Joseph 7=St Lucy 8=St Michael 9=St Peter 10=St Philip 11=St Thomas 99=ND
(40) regdate:		Y-M-D
(41) certifier:		Text, if missing=99
(42) certifieraddr:	Text, if missing=99
(43) namematch:		1=names match but different person 2=no name match
(44) death_certificate_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete
*/

** (1) record_id (auto-generated by REDCap)

** (2) redcap_event_name (auto-generated by REDCap)

** (3) dddoa: Y-M-D H:M, readonly
format dddoa %tcCCYY-NN-DD_HH:MM:SS
label var dddoa "ABS DateTime"

** (4) ddda
label var ddda "ABS DA"
label define ddda_lab 4 "KG" 13 "KWG" 14 "TH" 20 "NR" 25 "AH" 98 "intern", modify
label values ddda ddda_lab

** (5) odda
label var odda "ABS Other DA"

** (6) certtype: 1=MEDICAL 2=POST MORTEM 3=CORONER 99=ND, required
label var certtype "Certificate Type"
label define certtype_lab 1 "Medical" 2 "Post Mortem" 3 "Coroner" 99 "ND", modify
label values certtype certtype_lab

** (7) regnum: Text, if missing=9999
label var regnum "Registry Dept #"

** (8) district: 1=A 2=B 3=C 4=D 5=E 6=F
/* Districts are assigned based on death parish
	District A - anything below top rock christ church and st. michael 
	District B - anything above top rock christ church and st. george
	District C - st. philip and st. john
	District D - st. thomas
	District E - st. james, st. peter, st. lucy
	District F - st. joseph, st. andrew
*/
label var district "District"
label define district_lab 1 "A" 2 "B" 3 "C" 4 "D" 5 "E" 6 "F", modify
label values district district_lab

** (9) pname: Text, if missing=99
label var pname "Deceased's Name"

** (10) address: Text, if missing=99
label var address "Deceased's Address"

** (11) parish: 1=Christ Church 2=St Andrew 3=St George 4=St James 5=St John 6=St Joseph 7=St Lucy 8=St Michael 9=St Peter 10=St Philip 11=St Thomas 99=ND
label var parish "Deceased's Parish"
label define parish_lab 1 "Christ Church" 2 "St. Andrew" 3 "St. George" 4 "St. James" 5 "St. John" 6 "St. Joseph" ///
						7 "St. Lucy" 8 "St. Michael" 9 "St. Peter" 10 "St. Philip" 11 "St. Thomas" 99 "ND", modify
label values parish parish_lab

** (12) sex:	1=Male 2=Female 99=ND
label var sex "Sex"
label define sex_lab 1 "Male" 2 "Female" 99 "ND", modify
label values sex sex_lab

** (13) age: Integer - min=0, max=999
label var age "Age"

** (14) agetxt
label var agetxt "Age Qualifier"
label define agetxt_lab 1 "Minutes" 2 "Hours" 3 "Days" 4 "Weeks" 5 "Months" 6 "Years" 99 "ND", modify
label values agetxt agetxt_lab

** (15) nrnnd: 1=Yes 2=No
label var nrnnd "Is National ID # documented?"

** (16) nrn: dob-####, partial missing=dob-9999, if missing=.
label var nrn "National ID #"
format nrn %12.0g

** (17) mstatus: 1=Single 2=Married 3=Separated/Divorced 4=Widowed/Widow/Widower 9=ND
label var mstatus "Marital Status"
label define mstatus_lab 1 "Single" 2 "Married" 3 "Separated/Divorced" 4 "Widowed/Widow/Widower" 99 "ND", modify
label values mstatus mstatus_lab

STOPPED HERE
** (15) occu: Text, if missing=99
replace occu="99" if occu=="NIL"|occu=="ND"|occu=="" //944 real changes made
replace occu=upper(occu) //0 real changes made

** (16) durationnum: Integer - min=0, max=99, if missing=99
count if durtxt!="" //132
replace durtxt="" if durtxt=="99" //16 real changes made
list record_id durtxt if durtxt!=""
replace durtxt="2.5" if record_id==3263 //1 real change made
replace durtxt="10 M" if record_id==6113 //1 real change made
replace durtxt="" if record_id==6962 //1 real change made
replace durtxt="23 MONTHS" if record_id==13590 //1 real change made
replace durtxt="1 MONTH" if record_id==13638 //1 real change made
replace durtxt="3 MONTHS" if record_id==14462 //1 real change made
replace durtxt="3.25 YEARS" if record_id==15652 //1 real change made
replace durtxt="21 MONTHS" if record_id==18034 //1 real change made
replace durtxt="3 Y" if record_id==19564 //1 real change made
replace durtxt="3.25 YEARS" if record_id==21208 //1 real change made
replace durtxt="3 MONTHS" if record_id==22573 //1 real change made
replace durtxt="3 MONTHS" if record_id==23208 //1 real change made
replace durtxt="20 MONTHS" if record_id==23791 //1 real change made
split durtxt, destring
replace durtxt1=99 if durtxt1==. //24,073 real changes made
rename durtxt1 durationnum

** (17) durationtxt: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
gen byte durationtxt=.
replace durationtxt=1 if durtxt2=="D" | regexm(durtxt2, "DAY") //19 real changes made
replace durationtxt=2 if durtxt2=="W" | regexm(durtxt2, "WEEK") //8 real changes made
replace durationtxt=3 if durtxt2=="M" | regexm(durtxt2, "MON") //55 real changes made
replace durationtxt=4 if durtxt2=="Y" | regexm(durtxt2, "YEAR") //32 real changes made
count if durationtxt==. & durtxt2!="" //0

** (18) dod: Y-M-D
format dod %tdCCYY-NN-DD

** (19) deathyear: Integer
gen int deathyear=year(dod)

** (20) cod1a: Text, if missing=99
replace cod1a= subinstr(cod1a,"99","",.) if regexm(cod1a, "99") //2,364 real changes made
replace cod1a = rtrim(ltrim(itrim(cod1a))) //18,620 real changes made
replace cod1a=upper(cod1a) //9 real changes made

** (21) onsetnumcod1a: Integer - min=0, max=99, if missing=99
count if onsettxt!="" //132
replace onsettxt="" if onsettxt=="99" //46 real changes made
list record_id onsettxt if onsettxt!=""
replace onsettxt="32 MONTHS" if record_id==5612 //1 real change made
replace onsettxt="" if record_id==6962 //1 real change made
replace onsettxt="29 MONTHS" if record_id==10166 //1 real change made
replace onsettxt="1 YEAR" if record_id==11784 //1 real change made
replace onsettxt="2 M" if record_id==12762 //1 real change made
replace onsettxt="" if record_id==15482 //1 real change made
replace onsettxt="1.5 M" if record_id==18034 //1 real change made
replace onsettxt="5 YEARS" if record_id==19564 //1 real change made
split onsettxt, destring
replace onsettxt1=99 if onsettxt1==. //24,104 real changes made
rename onsettxt1 onsetnumcod1a

** (22) onsettxtcod1a: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
gen byte onsettxtcod1a=.
replace onsettxtcod1a=1 if onsettxt2=="D" | regexm(onsettxt2, "DAY") //2 real changes made
replace onsettxtcod1a=2 if onsettxt2=="W" | regexm(onsettxt2, "WEEK") //5 real changes made
replace onsettxtcod1a=3 if onsettxt2=="M" | regexm(onsettxt2, "MON") //47 real changes made
replace onsettxtcod1a=4 if onsettxt2=="Y" | regexm(onsettxt2, "YEAR") //30 real changes made
count if onsettxtcod1a==. & onsettxt2!="" //0

/*
(23) cod1b:			Text, if missing=99
(24) onsetnumcod1b:	Integer - min=0, max=99, if missing=99
(25) onsettxtcod1b:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(26) cod1c:			Text, if missing=99
(27) onsetnumcod1c:	Integer - min=0, max=99, if missing=99
(28) onsettxtcod1c:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(29) cod1d:			Text, if missing=99
(30) onsetnumcod1d:	Integer - min=0, max=99, if missing=99
(31) onsettxtcod1d:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(32) cod2a:			Text, if missing=99
(33) onsetnumcod2a:	Integer - min=0, max=99, if missing=99
(34) onsettxtcod2a:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
(35) cod2b:			Text, if missing=99
(36) onsetnumcod2b:	Integer - min=0, max=99, if missing=99
(37) onsettxtcod2b:	1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
*/
gen cod1b="99"
gen int onsetnumcod1b=.
gen byte onsettxtcod1b=.
gen cod1c="99"
gen int onsetnumcod1c=.
gen byte onsettxtcod1c=.
gen cod1d="99"
gen int onsetnumcod1d=.
gen byte onsettxtcod1d=.
gen cod2a="99"
gen int onsetnumcod2a=.
gen byte onsettxtcod2a=.
gen cod2b="99"
gen int onsetnumcod2b=.
gen byte onsettxtcod2b=.

** (38) pod: Text, if missing=99
replace pod="QEH" if pod=="QUEEN ELIZABETH HOSPITAL" | (regexm(pod, "BETH") & regexm(pod, "HOSP")) | (regexm(pod, "QUEEN") & regexm(pod, "ELIZ")) //9,610 real changes made
replace pod="GERIATRIC HOSPITAL" if regexm(pod, "GERIATRIC") //145 real changes made
replace pod="BAYVIEW HOSPITAL" if pod=="BAYVIEW" | (regexm(pod, "BAYVIEW") & regexm(pod, "HOSP")) | (regexm(pod, "BAYVIEW") & regexm(pod, "BECKLES")) //49 real changes made
replace pod="99" if pod=="ND" | pod=="" //418 real changes made
replace pod=upper(pod) //13 real changes made
replace pod = rtrim(ltrim(itrim(pod))) //25 real changes made

** (39) deathparish: 1=Christ Church 2=St Andrew 3=St George 4=St James 5=St John 6=St Joseph 7=St Lucy 8=St Michael 9=St Peter 10=St Philip 11=St Thomas 99=ND
gen int deathparish=.
replace deathparish=1 if regexm(deathpar, "CHRIST") //2,202 real changes made
replace deathparish=2 if regexm(deathpar, "DREW") //155 real changes made
replace deathparish=3 if regexm(deathpar, "GEO") //664 real changes made
replace deathparish=4 if regexm(deathpar, "JAM") //790 real changes made
replace deathparish=5 if regexm(deathpar, "JOHN") //316 real changes made
replace deathparish=6 if regexm(deathpar, "JOSE") //199 real changes made
replace deathparish=7 if regexm(deathpar, "LU") //374 real changes made
replace deathparish=8 if regexm(deathpar, "MICH") //17,624 real changes made
replace deathparish=9 if regexm(deathpar, "PET") //397 real changes made
replace deathparish=10 if regexm(deathpar, "PHIL") //993 real changes made
replace deathparish=11 if regexm(deathpar, "THOM") //457 real changes made
count if deathparish==. //17
list record_id deathpar if deathparish==.
replace deathparish=99 if deathparish==. //17 real changes made
drop deathpar

** (40) regdate: Y-M-D
format regdate %tdCCYY-NN-DD

** (41) certifier: Text, if missing=99
replace certifier="99" if certifier=="" //24,056 real changes made
replace certifier= subinstr(certifier,"."," ",.) if certifier!="" //7 real changes made
replace certifier=upper(certifier) //0 real changes made
replace certifier = rtrim(ltrim(itrim(certifier))) //0 real changes made

** (42) certifieraddr: Text, if missing=99
gen certifieraddr="99"

** (43) namematch: 1=names match but different person 2=no name match
count if namematch==. //0

** (44) death_certificate_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete
gen byte death_certificate_complete=2


** REMOVE variables not needed in DeathData REDCap database;
** ORDER variables according to position in DeathData REDCap database
drop deathid dbid regno natregno casefindingdate cftime regnumtemp durtxt2 onsettxt2
order record_id cfdate cfda certtype regnum district pname address parish sex ///
	  age nrnnd nrn mstatus occu durationnum durationtxt dod deathyear cod1a ///
	  onsetnumcod1a onsettxtcod1a cod1b onsetnumcod1b onsettxtcod1b cod1c ///
	  onsetnumcod1c onsettxtcod1c cod1d onsetnumcod1d onsettxtcod1d cod2a ///
	  onsetnumcod2a onsettxtcod2a cod2b onsetnumcod2b onsettxtcod2b pod ///
	  deathparish regdate certifier certifieraddr namematch death_certificate_complete


count // 24,188

label data "BNR MORTALITY data 2008-2017"
notes _dta :These data prepared from BB national death register & BNR (MS Access) deathdata database
save "data\raw\2008-2017_deaths_prepped.dta" ,replace
