** HEADER -----------------------------------------------------
**  DO-FILE METADATA
    //  algorithm name          2_clean_deaths.do
    //  project:                BNR
    //  analysts:               Jacqueline CAMPBELL
    //  date first created      27-MAY-2020
    // 	date last modified      27-MAY-2020
    //  algorithm task          Clean death data
    //  status                  Completed
    //  objectve                To have one dataset with cleaned 2019 death data.
    //  note                    Cleaned 2019 dataset to be merged with 2008-2020 death dataset; 
    //                          Redcap database with ALL cleaned deaths to be created.

    
    ** General algorithm set-up
    version 16
    clear all
    macro drop _all
    set more off

    ** Initialising the STATA log and allow automatic page scrolling
    capture {
            program drop _all
    	drop _all
    	log close
    	}

    ** Set working directories: this is for DATASET and LOGFILE import and export
    ** DATASETS to encrypted SharePoint folder
    local datapath "X:/The University of the West Indies/DataGroup - repo_data/data_p141"
    ** LOGFILES to unencrypted OneDrive folder (.gitignore set to IGNORE log files on PUSH to GitHub)
    local logpath X:/OneDrive - The University of the West Indies/repo_datagroup/repo_p141

    ** Close any open log file and open a new log file
    capture log close
    log using "`logpath'\2_clean_deaths_2019.smcl", replace
** HEADER -----------------------------------------------------

***************
** LOAD DATASET  
***************
use "`datapath'\version02\2-working\2019_deaths_prepped_dp"

count //2,195


*****************
** DATA QUALITY  
*****************
** Create quality report - corrections per DA
forvalues j=1/56 {
	gen flag`j'=0
}

label var flag1 "Record ID"
label var flag2 "Redcap Event"
label var flag3 "ABS DateTime"
label var flag4 "ABS DA"
label var flag5 "ABS Other DA"
label var flag6 "Certificate Type"
label var flag7 "ABS Reg Dept #"
label var flag8 "ABS District"
label var flag9 "Pt Name"
label var flag10 "Pt Address"
label var flag11 "Pt Parish"
label var flag12 "Sex"
label var flag13 "Age"
label var flag14 "Age (time period)"
label var flag15 "Date of Death"
label var flag16 "Death Year"
label var flag17 "NRN documented?"
label var flag18 "NRN"
label var flag19 "Marital Status"
label var flag20 "Occupation"
label var flag21 "Duration"
label var flag22 "Duration (time period)"
label var flag23 "COD 1a"
label var flag24 "Onset 1a"
label var flag25 "Onset 1a (time period)"
label var flag26 "COD 1b"
label var flag27 "Onset 1b"
label var flag28 "Onset 1b (time period)"
label var flag29 "COD 1c"
label var flag30 "Onset 1c"
label var flag31 "Onset 1c (time period)"
label var flag32 "COD 1d"
label var flag33 "Onset 1d"
label var flag34 "Onset 1d (time period)"
label var flag35 "COD 2a"
label var flag36 "Onset 2a"
label var flag37 "Onset 2a (time period)"
label var flag38 "COD 2b"
label var flag39 "Onset 2b"
label var flag40 "Onset 2b (time period)"
label var flag41 "Place of Death"
label var flag42 "Death Parish"
label var flag43 "Reg Date"
label var flag44 "Certifier"
label var flag45 "Certifer Address"
label var flag46 "Name Match"
label var flag47 "Cleaned?"
label var flag48 "ABS Complete?"
label var flag49 "TF DateTime"
label var flag50 "TF DA"
label var flag51 "TF Reg # START"
label var flag52 "TF District START"
label var flag53 "TF Reg # END"
label var flag54 "TF District END"
label var flag55 "TF Comments"
label var flag56 "TF Complete?"


gen corr_AH=0 //DA code=25
gen corr_KG=0 //DA code=04
gen corr_NR=0 //DA code=20
gen corr_KWG=0 //DA code=13
gen corr_TH=0 //DA code=14
gen corr_intern=0 //DA code=98


*****************
** DATA CLEANING  
*****************
** CLEAN each variable according to below consistency checks and the quality rules in DeathData REDCap database

************************
**  DEATH CERTIFICATE **
**        FORM        **
************************
sort record_id
** record_id (auto-generated by REDCap): FLAG 1
** (1) missing/duplicate
count if record_id==. //0
duplicates list record_id, nolabel sepby(record_id) //1 - record_id=29

** event (auto-generated by REDCap): FLAG 2
** (2) missing
count if event==. //0


** dddoa: Y-M-D H:M, readonly: FLAG 3
** (3) missing
count if event==1 & dddoa==. //0


** ddda: FLAG 4
** (4) missing
count if event==1 & ddda==. //0
count if event==1 & (ddda!=4 & ddda!=13 & ddda!=14 & ddda!=20 & ddda!=25 & ddda!=98) //0
//list record_id ddda if event==1 & (ddda!=4 & ddda!=13 & ddda!=14 & ddda!=20 & ddda!=25 & ddda!=98)
replace ddda=20 if record_id==1325 //1 change
replace flag4=flag4+1 if record_id==1325
replace corr_NR=corr_NR+1 if record_id==1325

** odda: FLAG 5
** (5) missing
count if ddda==98 & odda=="" //0
** (6) invalid
count if ddda!=98 & odda!="" //
//list record_id event dddoa ddda odda if ddda!=98 & odda!=""


** certtype: 1=MEDICAL 2=POST MORTEM 3=CORONER 99=ND, required: FLAG 6
** (7) missing
count if event==1 & certtype==. //0
//list record_id event dddoa ddda certtype if event==1 & certtype==.


** regnum: integer, if missing=9999: FLAG 7
** (8) missing
count if event==1 & regnum==.|event==1 & regnum==0 //0
** (9) invalid
count if event==1 & regnum>9999 //0


** district: 1=A 2=B 3=C 4=D 5=E 6=F: FLAG 8
** (10) missing
count if event==1 & district==. //0


** pname: Text, if missing=99: FLAG 9
** (11) missing
count if event==1 & pname=="" //0
** (12) invalid
count if event==1 & regexm(pname, "[a-z]") //2 - query with KG re 1853 in 2019 db
//list record_id event ddda pname if event==1 & regexm(pname, "[a-z]")
replace pname=subinstr(pname,"Suspected to be ","",.) if record_id==129
replace flag9=flag9+1 if record_id==129 //1 change
replace corr_intern=corr_intern+1 if record_id==129 //1 change
replace corr_KG=corr_KG+1 if record_id==1853 //1 change
//replace pname=upper(pname) // changes
//replace corr_KG=corr_KG+1 if record_id==360 //1 change
//replace corr_AH=corr_AH+1 if record_id==1122 //1 change
count if event==1 & regexm(pname,"NIL")|event==1 & regexm(pname,"ND") //190 - all correct
//list record_id ddda pname if event==1 & regexm(pname,"NIL")|event==1 & regexm(pname,"ND")
** (13) duplicate
sort pname
quietly by pname:  gen dup = cond(_N==1,0,_n)
sort pname
count if event==1 & dup>0  //90 - some are exact replicas as AH seem to import data twice from Redcap BNRDeathData db into BNRDeathData_2018 db
sort pname record_id
//list record_id dddoa ddda pname regnum district nrn if event==1 & dup>0
replace namematch=1 if record_id==219|record_id==309|record_id==1823|record_id==517|record_id==1871 ///
					   |record_id==273|record_id==1314|record_id==143|record_id==458|record_id==738 ///
					   |record_id==190|record_id==1919|record_id==416|record_id==771|record_id==1049 ///
					   |record_id==575|record_id==1137|record_id==696|record_id==1768|record_id==616 ///
					   |record_id==269|record_id==820|record_id==353|record_id==712|record_id==1655 ///
					   |record_id==2151|record_id==1866|record_id==526 //28 changes

drop if record_id==357|record_id==461 //2 deleted
drop dup


** address: Text, if missing=99: FLAG 10
** (14) missing
count if event==1 & address=="" //0
** (15) invalid 
count if event==1 & regexm(address, "[a-z]") //1 - #1853 query for KG
//list record_id event ddda address if event==1 & regexm(address, "[a-z]")
//replace address=upper(address) //3 changes
replace flag10=flag10+1 if record_id==1853 //1 change
replace corr_KG=corr_KG+1 if record_id==1853 //1 change
count if event==1 & regexm(address,"NIL")|event==1 & regexm(address,"ND") //399 - all correct
//list record_id ddda address if event==1 & regexm(address,"NIL")|event==1 & regexm(address,"ND")


** parish: FLAG 11
** (16) missing
count if event==1 & parish==. //0


** sex:	1=Male 2=Female 99=ND: FLAG 12
** (17) missing
count if event==1 & sex==. //0
//list record_id event ddda pname sex if event==1 & sex==.
** (18) invalid - female with prostate
count if sex==2 & (regexm(cod1a, "PROSTAT")|regexm(cod1b, "PROSTAT")|regexm(cod1c, "PROSTAT") ///
		|regexm(cod1d, "PROSTAT")|regexm(cod2a, "PROSTAT")|regexm(cod2b, "PROSTAT")) //1
//list record_id ddda pname nrn sex cod* if (regexm(cod1a, "PROSTAT")|regexm(cod1b, "PROSTAT")|regexm(cod1c, "PROSTAT")|regexm(cod1d, "PROSTAT")|regexm(cod2a, "PROSTAT")|regexm(cod2b, "PROSTAT")) & sex==2
recode sex 2=1 if record_id==1634 //1 change
replace flag12=flag12+1 if record_id==1634 //1 change
replace corr_intern=corr_intern+1 if record_id==1634 //1 change
** (19) visual check - first names for those missing nrn
count if sex==1 & nrn==. //70 - check if there is a stata check for this e.g. soundex,etc - 0 changes
//list record_id ddda pname sex if sex==1 & nrn==.
//recode sex 1=2 if record_id== //0 changes
//replace corr_AH=corr_AH+1 if record_id==1311|record_id==1309 //2 changes
//replace corr_KG=corr_KG+1 if record_id==891 //1 change
//replace corr_NR=corr_NR+1 if record_id==1723 //1 change
** (20) invalid - male with female genital cod
count if sex==1 & (regexm(cod1a, "UTER") | regexm(cod1a, "OMA OF THE VULVA") | ///
			regexm(cod1a, "CHORIOCARCIN") | regexm(cod1a, "ENDOMETRIAL CARCINOMA") | ///
			regexm(cod1a, "ENDOMETRIAL CANC") | regexm(cod1a, "OF ENDOMETRIUM") | ///
			regexm(cod1a, "OF THE ENDOMETRIUM") | regexm(cod1a, "VULVA CARCINOMA") | ///
			regexm(cod1a, "VULVAL CANCER") | regexm(cod1a, "VAGINAL CARCINOMA")|regexm(cod1a, "ENDOMETRIUM")) //1
/*list record_id ddda pname nrn sex cod* if sex==1 & (regexm(cod1a, "UTER") | regexm(cod1a, "OMA OF THE VULVA") | ///
			regexm(cod1a, "CHORIOCARCIN") | regexm(cod1a, "ENDOMETRIAL CARCINOMA") | ///
			regexm(cod1a, "ENDOMETRIAL CANC") | regexm(cod1a, "OF ENDOMETRIUM") | ///
			regexm(cod1a, "OF THE ENDOMETRIUM") | regexm(cod1a, "VULVA CARCINOMA") | ///
			regexm(cod1a, "VULVAL CANCER") | regexm(cod1a, "VAGINAL CARCINOMA")|regexm(cod1a, "ENDOMETRIUM"))
*/
recode sex 1=2 if record_id==70|record_id==711 //2 changes
replace flag12=flag12+1 if record_id==70|record_id==711 //2 changes
replace corr_KG=corr_KG+1 if record_id==70|record_id==711 //2 changes
** (21) visual check - first names for those missing nrn
count if sex==2 & nrn==. //44 - check if there is a stata check for this e.g. soundex,etc - 0 changes
//list record_id ddda pname sex if sex==2 & nrn==.


** age: Integer - min=0, max=999: FLAG 13
** (22) missing
count if event==1 & age==. //0
** (23) missing - NRN not missing
count if (age==.|age==0) & nrn!=. //0


** agetxt - 1 "Minutes" 2 "Hours" 3 "Days" 4 "Weeks" 5 "Months" 6 "Years" 99 "ND": FLAG 14
** (25) missing
count if age!=. & agetxt==. //0
** (26) invalid
count if age==999 & agetxt!=99 //0
** (27) visual check - NRN vs agetxt
count if nrn!=. & age!=. & agetxt!=6 //5
//list record_id ddda dod nrn age agetxt if nrn!=. & age!=. & agetxt!=6 //checked these using redcap db & electoral list
replace agetxt=6 if record_id==1806|record_id==1850 //2 changes
replace flag14=flag14+1 if record_id==1806|record_id==1850 //2 changes
replace corr_KG=corr_KG+1 if record_id==1806|record_id==1850 //2 changes


** dod: Y-M-D (need to clean dod before other checks): FLAG 15
** (28) missing
count if event==1 & dod==. //0
** (29) invalid - future date
gen currentd=c(current_date)
gen double today=date(currentd, "DMY")
drop currentd
format today %tdCCYY-NN-DD
count if event==1 & dod>today //0
sort record_id
//list record_id ddda dod regdate pname if event==1 & dod>today
** (30) invalid - after reg date
count if event==1 & dod>regdate //10 (check redcapdb for if any coroner cases; 2019 TF redcap report for 'true' 2019 cases)
//list record_id ddda dod regdate pname if event==1 & dod>regdate
replace dod=d(27dec2018) if record_id==94 //1 change
replace corr_KG=corr_KG+1 if record_id==94|record_id==918|record_id==1747|record_id==1748|record_id==1878 //5 changes
replace corr_intern=corr_intern+1 if record_id==51|record_id==137|record_id==1536 //3 changes
replace corr_AH=corr_AH+1 if record_id==159 //1 change
replace corr_TH=corr_TH+1 if record_id==349 //1 change
//swapval regdate dod if dod>regdate //ssc install swapval - doesn't work for dates, only for numeric or string values
replace flag15=flag15+1 if dod>regdate
gen dod2=regdate if dod>regdate
gen regdate2=dod if dod>regdate
format dod2 regdate2 %tdCCYY-NN-DD
replace dod=dod2 if dod2!=. //9 changes
replace regdate=regdate2 if regdate2!=. //9 changes
drop dod2 regdate2



** dodyear (not included in single year Redcap db but done for multi-year Redcap db): FLAG 16
** (31) missing
count if event==1 & dodyear==. //0
//list record_id ddda dod regdate if event==1 & dodyear==.
** (32) invalid - deaths before/after 2019
count if event==1 & dodyear!=2019 //3
//list record_id ddda dod dodyear regdate if event==1 & dodyear!=2019
//tab dodyear if event==1,m
/*
    Year of |
      Death |      Freq.     Percent        Cum.
------------+-----------------------------------
       2018 |          2        0.09        0.09 - Checked these against previously-collected 2017 deaths and 0 matches
       2019 |      2,137       99.86       99.95
       2020 |          1        0.05      100.00 - Checked with KG and this is a dummy record so remove from dataset
------------+-----------------------------------
      Total |      2,140      100.00
*/
//drop if event==1 & dodyear>2019 - forgot to drop at this point but need to do so for next year's cleaning

** nrnnd: 1=Yes 2=No: FLAG 17
** (33) missing
count if event==1 & nrnnd==. //0
//list record_id ddda nrn if event==1 & nrnnd==.
** (34) invalid
count if event==1 & nrn==. & nrnnd==1 //0
** (35) invalid
count if nrn!=. & nrnnd==2 //0

** nrn: dob-####, partial missing=dob-9999, if missing=.: FLAG 18
tostring nrn, gen(natregno) format("%15.0f")
replace natregno="" if natregno=="." //166 changes
** (36) missing
count if event==1 & nrnnd==1 & (natregno==""|natregno=="9999999999") //0
** (37) invalid - length (checked against electoral list; no error for DA if leading zero was in redcap db)
count if natregno!="" & length(natregno)!=10 //18
//list record_id ddda pname nrn natregno if natregno!="" & length(natregno)!=10
replace flag18=flag18+1 if record_id==277|record_id==313|record_id==377|record_id==420|record_id==487 ///
						  |record_id==650|record_id==882|record_id==903|record_id==921|record_id==936 ///
						  |record_id==958|record_id==1261|record_id==1332|record_id==1341|record_id==1825 ///
						  |record_id==1903|record_id==1975|record_id==2006 //18 changes
replace corr_intern=corr_intern+1 if record_id==277 //1 change
replace corr_NR=corr_NR+1 if record_id==313 //1 change
replace corr_AH=corr_AH+1 if record_id==377 //1 change
replace corr_KG=corr_KG+1 if record_id==420|record_id==487|record_id==650|record_id==882|record_id==903 ///
							|record_id==921|record_id==936|record_id==958|record_id==1261|record_id==1332 ///
							|record_id==1341|record_id==1825|record_id==1903|record_id==1975|record_id==2006 //15 changes
replace natregno=subinstr(natregno,"6","69999",.) if record_id==277 //1 change
replace natregno=subinstr(natregno,"09","009",.) if record_id==313 //1 change
replace natregno=subinstr(natregno,"6","06",.) if record_id==377 //1 change
replace natregno=subinstr(natregno,"3","39999",.) if record_id==420 //1 change
replace natregno=subinstr(natregno,"82","01082",.) if record_id==487 //1 change
replace natregno=subinstr(natregno,"2","02",.) if record_id==650 //1 change
replace natregno=subinstr(natregno,"04","004",.) if record_id==882 //1 change
replace natregno=subinstr(natregno,"00","0",.) if record_id==903 //1 change
replace natregno=subinstr(natregno,"509","0509",.) if record_id==921 //1 change
replace natregno=subinstr(natregno,"05","005",.) if record_id==936 //1 change
replace natregno=subinstr(natregno,"9","",.) if record_id==958 //1 change
replace natregno=subinstr(natregno,"1","01",.) if record_id==1261 //1 change
replace natregno=subinstr(natregno,"7","07",.) if record_id==1332 //1 change
replace natregno=subinstr(natregno,"5","59999",.) if record_id==1341 //1 change
replace natregno=subinstr(natregno,"20","2",.) if record_id==1825 //1 change
replace natregno="" if record_id==1903 //1 change
replace nrnnd=2 if record_id==1903 //1 change
replace natregno=subinstr(natregno,"2","0002",.) if record_id==1975 //1 change
replace natregno=subinstr(natregno,"4","49999",.) if record_id==2006 //1 change

** (38) invalid - dob but missing nrn #
count if regexm(natregno,"9999")|regexm(natregno,"99") //22 (checked against electoral list)
//list record_id ddda natregno pname if regexm(natregno,"9999")|regexm(natregno,"99")
replace natregno=subinstr(natregno,"9999","0087",.) if record_id==277 //1 change
replace natregno=subinstr(natregno,"99","00",.) if record_id==373 //1 change
replace natregno=subinstr(natregno,"9999","0045",.) if record_id==420 //1 change
replace natregno=subinstr(natregno,"99","00",.) if record_id==815 //1 change
replace natregno=subinstr(natregno,"9999","0163",.) if record_id==1341 //1 change
replace natregno=subinstr(natregno,"99","00",.) if record_id==1351 //1 change
replace natregno=subinstr(natregno,"99","00",.) if record_id==1904 //1 change
replace natregno=subinstr(natregno,"9999","0018",.) if record_id==2006 //1 change
replace flag18=flag18+1 if record_id==277|record_id==373|record_id==420|record_id==815|record_id==1341|record_id==1904|record_id==2006 //7 changes
** (39) invalid - female with 'male' NRN
count if sex==2 & (regex(substr(natregno,-2,1), "[1,3,5,7,9]")) & !(strmatch(strupper(natregno), "*-9999*")) //4
//list record_id ddda pname natregno sex cod* if sex==2 & (regex(substr(natregno,-2,1), "[1,3,5,7,9]")) & !(strmatch(strupper(natregno), "*-9999*"))
//recode sex 2=1 if record_id== //0 changes
//replace flag12=flag12+1 if record_id== //0 changes
** (40) invalid - male with 'female' NRN
count if sex==1 & regex(substr(natregno,-2,1), "[0,2,4,6,8]") //12
//list record_id ddda pname natregno sex cod* if sex==1 & regex(substr(natregno,-2,1), "[0,2,4,6,8]")
recode sex 1=2 if record_id==571|record_id==577|record_id==588|record_id==721|record_id==1041|record_id==1177|record_id==1663 //7 changes
replace flag12=flag12+1 if record_id==571|record_id==577|record_id==588|record_id==721|record_id==1041|record_id==1177|record_id==1663 //6 changes
replace corr_KG=corr_KG+1 if record_id==571|record_id==577|record_id==588|record_id==721|record_id==1041|record_id==1177|record_id==1663 //7 changes
** (41) invalid - age vs dob(nrn)
gen dobyr=substr(natregno, 1, 2) if natregno!=""
gen dobmon=substr(natregno, 3, 2) if natregno!=""
gen dobday=substr(natregno, 5, 2) if natregno!=""
count if (agetxt!=6 & natregno!="")|regex(substr(dobyr,1,1),"[0]") //10
//list record_id age agetxt dod natregno dobyr dobmon dobday if (agetxt!=6 & natregno!="")|regex(substr(dobyr,1,1),"[0]")
replace dobyr="20"+dobyr if (agetxt!=6 & natregno!="")|regex(substr(dobyr,1,1),"[0]") //10 changes
replace dobyr="19"+dobyr if length(dobyr)==2 //2,016 changes
count if length(dobyr)>4 //0
count if dobday!="" & (dobday!="01"&dobday!="02"&dobday!="03"&dobday!="04"&dobday!="05"&dobday!="06"&dobday!="07"&dobday!="08"&dobday!="09"&dobday!="10"&dobday!="11"&dobday!="12" ///
		 &dobday!="13"&dobday!="14"&dobday!="15"&dobday!="16"&dobday!="17"&dobday!="18"&dobday!="19"&dobday!="20"&dobday!="21"&dobday!="22"&dobday!="23"&dobday!="24"&dobday!="25" ///
		 &dobday!="26"&dobday!="27"&dobday!="28"&dobday!="29"&dobday!="30"&dobday!="31") //4 - query KG re 1853
/*list record_id ddda dobday natregno pname if dobday!="" & (dobday!="01"&dobday!="02"&dobday!="03"&dobday!="04"&dobday!="05"&dobday!="06"&dobday!="07"&dobday!="08"&dobday!="09"&dobday!="10"&dobday!="11"&dobday!="12" ///
		 &dobday!="13"&dobday!="14"&dobday!="15"&dobday!="16"&dobday!="17"&dobday!="18"&dobday!="19"&dobday!="20"&dobday!="21"&dobday!="22"&dobday!="23"&dobday!="24"&dobday!="25" ///
		 &dobday!="26"&dobday!="27"&dobday!="28"&dobday!="29"&dobday!="30"&dobday!="31")
*/
replace dobday="31" if record_id==215 //1 change
replace natregno=subinstr(natregno,"32","31",.) if record_id==215 //1 change
replace dobday="03" if record_id==1322 //1 change
replace natregno=subinstr(natregno,"43","03",.) if record_id==1322 //1 change
replace dobday="23" if record_id==1346 //1 change
replace natregno=subinstr(natregno,"83","23",.) if record_id==1346 //1 change
replace flag18=flag18+1 if record_id==215|record_id==1322|record_id==1346 //3 changes
replace corr_NR=corr_NR+1 if record_id==1322 //1 change
replace corr_KG=corr_KG+1 if record_id==215|record_id==1346 //2 changes

count if dobmon!="" & (dobmon!="01"&dobmon!="02"&dobmon!="03"&dobmon!="04"&dobmon!="05"&dobmon!="06"&dobmon!="07"&dobmon!="08"&dobmon!="09"&dobmon!="10"&dobmon!="11"&dobmon!="12") //4 - query KG re 1853
//list record_id ddda dobmon natregno pname if dobmon!="" & (dobmon!="01"&dobmon!="02"&dobmon!="03"&dobmon!="04"&dobmon!="05"&dobmon!="06"&dobmon!="07"&dobmon!="08"&dobmon!="09"&dobmon!="10"&dobmon!="11"&dobmon!="12")
replace dobmon="06" if record_id==545 //1 change
replace natregno=subinstr(natregno,"09","90",.) if record_id==545 //1 change
replace dobmon="09" if record_id==622 //1 change
replace natregno=subinstr(natregno,"2","0",.) if record_id==622 //1 change
replace dobmon="11" if record_id==1874 //1 change
replace natregno=subinstr(natregno,"115","511",.) if record_id==1874 //1 change
replace flag18=flag18+1 if record_id==545|record_id==622|record_id==1874 //2 changes
replace corr_AH=corr_AH+1 if record_id==545 //1 change
replace corr_KG=corr_KG+1 if record_id==622|record_id==1874 //2 changes

gen birthdate=dobyr+dobmon+dobday
gen dob=date(birthdate, "YMD")
format dob %tdCCYY-NN-DD
gen age2=int((dod - dob)/365.25) //now use this to assign missing age
count if age!=age2 & natregno!="" & dob!=. //54
sort record_id
//list record_id age age2 agetxt dod dob natregno if age!=age2 & natregno!=""
replace age=95 if record_id==7 //1 change
replace agetxt=6 if record_id==7 //1 change
replace age=age2 if age!=age2 & natregno!="" & dob!=. & record_id!=7 & record_id!=99 & record_id!=545 & record_id!=849 & record_id!=1270 & record_id!=1874 & record_id!=2075 //47 changes
replace age=78 if record_id==1199
replace corr_NR=corr_NR+1 if record_id==7 //1 change
drop nrn dob dobday dobmon dobyr age2
rename natregno nrn


** mstatus: 1=Single 2=Married 3=Separated/Divorced 4=Widowed/Widow/Widower 99=ND: FLAG 19
** (42) missing
count if event==1 & mstatus==. //0


** occu: Text, if missing=99: FLAG 20
** (43) missing
count if event==1 & occu=="" //0
** (44) invalid 
count if event==1 & regexm(occu, "[a-z]") //2 - query KG re 1853
//list record_id ddda occu if event==1 & regexm(occu, "[a-z]")
replace occu="99" if record_id==291 //1 change
//replace occu=upper(occu) //0 changes
replace occu = rtrim(ltrim(itrim(occu))) //0 changes
replace flag20=flag20+1 if record_id==291 //1 change
replace corr_intern=corr_intern+1 if record_id==291
count if event==1 & regexm(occu,"NIL")|event==1 & regexm(occu,"ND") //103
//list record_id ddda occu if event==1 & regexm(occu,"NIL")|event==1 & regexm(occu,"ND")
count if event==1 & occu=="NIL"|event==1 & occu=="ND" //5
//list record_id ddda occu if event==1 & occu=="NIL"|event==1 & occu=="ND"
replace flag20=flag20+1 if event==1 & occu=="NIL"|event==1 & occu=="ND" //5 changes
replace occu="99" if event==1 & occu=="NIL"|event==1 & occu=="ND" //5 changes
replace corr_NR=corr_NR+1 if record_id==2 //1 change
replace corr_intern=corr_intern+1 if record_id==113|record_id==1699|record_id==1772|record_id==1783 //4 changes


** durationnum: Integer - min=0, max=99, if missing=99: FLAG 21
** (45) missing
count if event==1 & durationnum==. //0
** (46) invalid
count if durationnum==999 & durationtxt!=99 //29 - all correct
//list record_id ddda durationnum durationtxt if durationnum==999 & durationtxt!=99
//replace durationtxt=99 if durationnum==999 & durationtxt!=99 //39 changes
count if durationnum==99 & durationtxt==99 //1
//list record_id ddda durationnum durationtxt if durationnum==99 & durationtxt==99
replace flag21=flag21+1 if durationnum==99 & durationtxt==99 //1 change
replace corr_intern=corr_intern+1 if record_id==1510
replace durationnum=999 if durationnum==99 & durationtxt==99 //1 change


** durationtxt - 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 22
** (47) missing
count if durationnum!=. & durationtxt==. //0
//list record_id ddda durationnum durationtxt if durationnum!=. & durationtxt==.
** (48) possibly invalid
count if durationnum!=999 & durationtxt==99 //2 - 1 incorrect; 1 correct
//list record_id ddda durationnum durationtxt onset* if durationnum!=999 & durationtxt==99
replace flag22=flag22+1 if record_id==351 //1 change
replace durationtxt=4 if record_id==351 //1 change


** cod1a: Text, if missing=99: FLAG 23
** (49) missing
count if event==1 & cod1a=="" //0
** (50) invalid
count if event==1 & regexm(cod1a, "[a-z]") //0
//list record_id ddda cod1a onsetnumcod1a onsettxtcod1a if event==1 & regexm(cod1a, "[a-z]")
//replace cod1a=upper(cod1a) //0 changes
replace cod1a = rtrim(ltrim(itrim(cod1a))) //3 changes
count if event==1 & regexm(cod1a,"NIL")|event==1 & regexm(cod1a,"ND") //160 - all correct
//list record_id ddda cod1a if event==1 & regexm(cod1a,"NIL")|event==1 & regexm(cod1a,"ND")


** onsetnumcod1a: Integer - min=0, max=99, if missing=99: FLAG 24
** (51) missing
count if event==1 & cod1a!="99" & onsetnumcod1a==. //0
** (52) possibly invalid
count if onsetnumcod1a==999 & onsettxtcod1a!=99 //73 - all correct
//list record_id ddda onsetnumcod1a onsettxtcod1a if onsetnumcod1a==999 & onsettxtcod1a!=99
count if onsetnumcod1a==99 & onsettxtcod1a==99 //3
//list record_id ddda onsetnumcod1a onsettxtcod1a if onsetnumcod1a==99 & onsettxtcod1a==99
replace flag24=flag24+1 if onsetnumcod1a==99 & onsettxtcod1a==99 //3 changes
replace onsetnumcod1a=999 if onsetnumcod1a==99 & onsettxtcod1a==99 //3 changes
replace corr_intern=corr_intern+1 if record_id==1498|record_id==1528|record_id==1781


** onsettxtcod1a: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 25
** (53) missing
count if onsetnumcod1a!=. & onsettxtcod1a==. //0
//list record_id ddda onsetnumcod1a onsettxtcod1a if onsetnumcod1a!=. & onsettxtcod1a==.
count if onsetnumcod1a==999 & onsettxtcod1a==. //0
** (54) possibly invalid
count if onsetnumcod1a!=999 & onsettxtcod1a==99 //5
//list record_id ddda duration* onsetnumcod1a onsettxtcod1a onset* if onsetnumcod1a!=999 & onsettxtcod1a==99
replace flag25=flag25+1 if onsetnumcod1a!=999 & onsettxtcod1a==99 & record_id!=1678 //4 changes
replace onsettxtcod1a=2 if record_id==640
replace onsettxtcod1a=3 if record_id==744
replace onsettxtcod1a=1 if record_id==807
replace onsettxtcod1a=4 if record_id==829


** cod1b: Text, if missing=99: FLAG 26
** (55) missing
count if event==1 & cod1b=="" //0
** (56) invalid
count if event==1 & regexm(cod1b, "[a-z]") //0
//list record_id ddda cod1b onsetnumcod1b onsettxtcod1b if event==1 & regexm(cod1b, "[a-z]")
//replace cod1b=upper(cod1b) //0 changes
replace cod1b = rtrim(ltrim(itrim(cod1b))) //2 changes
count if event==1 & regexm(cod1b,"NIL")|event==1 & regexm(cod1b,"ND") //70 - all correct
//list record_id ddda cod1b if event==1 & regexm(cod1b,"NIL")|event==1 & regexm(cod1b,"ND")


** onsetnumcod1b: Integer - min=0, max=99, if missing=99: FLAG 27
** (57) missing
count if event==1 & cod1b!="99" & onsetnumcod1b==. //0
** (58) possibly invalid
count if onsetnumcod1b==999 & onsettxtcod1b!=99 //59 - all correct
//list record_id ddda onsetnumcod1b onsettxtcod1b if onsetnumcod1b==999 & onsettxtcod1b!=99
count if onsetnumcod1b==99 & onsettxtcod1b==99 //0
//list record_id ddda onsetnumcod1b onsettxtcod1b if onsetnumcod1b==99 & onsettxtcod1b==99


** onsettxtcod1b: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 28
** (59) missing
count if onsetnumcod1b!=. & onsettxtcod1b==. //0
//list record_id ddda onsetnumcod1b onsettxtcod1b if onsetnumcod1b!=. & onsettxtcod1b==.
count if onsetnumcod1b==999 & onsettxtcod1b==. //
** (60) possibly invalid
count if onsetnumcod1b!=999 & onsettxtcod1b==99 //4
//list record_id ddda duration* onsetnumcod1b onsettxtcod1b onset* if onsetnumcod1b!=999 & onsettxtcod1b==99
replace flag28=flag28+1 if onsetnumcod1b!=999 & onsettxtcod1b==99 & record_id!=1643 //3 changes
replace onsettxtcod1b=2 if record_id==640
replace onsettxtcod1b=3 if record_id==744
replace onsettxtcod1b=1 if record_id==807



** cod1c: Text, if missing=99: FLAG 29
** (61) missing
count if event==1 & cod1c=="" //0
** (62) invalid
count if event==1 & regexm(cod1c, "[a-z]") //0
//list record_id ddda cod1c onsetnumcod1c onsettxtcod1c if event==1 & regexm(cod1c, "[a-z]")
//replace cod1c=upper(cod1c) //0 changes
replace cod1c = rtrim(ltrim(itrim(cod1c))) //1 change
count if event==1 & regexm(cod1c,"NIL")|event==1 & regexm(cod1c,"ND") //20 - all correct
//list record_id ddda cod1c if event==1 & regexm(cod1c,"NIL")|event==1 & regexm(cod1c,"ND")


** onsetnumcod1c: Integer - min=0, max=99, if missing=99: FLAG 30
** (63) missing
count if event==1 & cod1c!="99" & onsetnumcod1c==. //0
//list record_id ddda cod1c onsetnumcod1c onsettxtcod1c if event==1 & cod1c!="99" & onsetnumcod1c==.
** (64) possibly invalid
count if onsetnumcod1c==999 & onsettxtcod1c!=99 //26 - all correct
//list record_id ddda onsetnumcod1c onsettxtcod1c if onsetnumcod1c==999 & onsettxtcod1c!=99
count if onsetnumcod1c==99 & onsettxtcod1c==99 //0
//list record_id ddda onsetnumcod1c onsettxtcod1c if onsetnumcod1c==99 & onsettxtcod1c==99


** onsettxtcod1c: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 31
** (65) missing
count if onsetnumcod1c!=. & onsettxtcod1c==. //0
//list record_id ddda onsetnumcod1c onsettxtcod1c if onsetnumcod1c!=. & onsettxtcod1c==.
count if onsetnumcod1c==999 & onsettxtcod1c==. //0
** (66) possibly invalid
count if onsetnumcod1c!=999 & onsettxtcod1c==99 //2
//list record_id ddda duration* onsetnumcod1c onsettxtcod1c onset* if onsetnumcod1c!=999 & onsettxtcod1c==99
replace flag28=flag28+1 if onsetnumcod1c!=999 & onsettxtcod1c==99 & record_id!=1570 //1 changes
replace onsettxtcod1c=3 if record_id==744


** cod1d: Text, if missing=99: FLAG 32
** (67) missing
count if event==1 & cod1d=="" //0
//list record_id ddda cod1d if event==1 & cod1d==""
** (68) invalid
count if event==1 & regexm(cod1d, "[a-z]") //0
//list record_id ddda cod1d onsetnumcod1d onsettxtcod1d if event==1 & regexm(cod1d, "[a-z]")
//replace cod1d=upper(cod1d) //0 changes
replace cod1d = rtrim(ltrim(itrim(cod1d))) //2 changes
count if event==1 & regexm(cod1d,"NIL")|event==1 & regexm(cod1d,"ND") //3 - all correct
//list record_id ddda cod1d if event==1 & regexm(cod1d,"NIL")|event==1 & regexm(cod1d,"ND")


** onsetnumcod1d: Integer - min=0, max=99, if missing=99: FLAG 33
** (69) missing
count if event==1 & cod1d!="99" & onsetnumcod1d==. //0
//list record_id ddda cod1d onsetnumcod1d onsettxtcod1d if event==1 & cod1d!="99" & onsetnumcod1d==.
** (70) possibly invalid
count if onsetnumcod1d==999 & onsettxtcod1d!=99 //12 - all correct
//list record_id ddda onsetnumcod1d onsettxtcod1d if onsetnumcod1d==999 & onsettxtcod1d!=99
count if onsetnumcod1d==99 & onsettxtcod1d==99 //0
//list record_id ddda onsetnumcod1d onsettxtcod1d if onsetnumcod1d==99 & onsettxtcod1d==99


** onsettxtcod1d: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 34
** (71) missing
count if onsetnumcod1d!=. & onsettxtcod1d==. //0
//list record_id ddda onsetnumcod1d onsettxtcod1d if onsetnumcod1d!=. & onsettxtcod1d==.
count if onsetnumcod1d==999 & onsettxtcod1d==. //0
** (72) possibly invalid
count if onsetnumcod1d!=999 & onsettxtcod1d==99 //0
//list record_id ddda duration* onsetnumcod1d onsettxtcod1d onset* if onsetnumcod1d!=999 & onsettxtcod1d==99


** cod2a: Text, if missing=99: FLAG 35
** (73) missing
count if event==1 & cod2a=="" //0
//list record_id ddda cod2a if event==1 & cod2a==""
** (74) invalid
count if event==1 & regexm(cod2a, "[a-z]") //0
//list record_id ddda cod2a onsetnumcod2a onsettxtcod2a if event==1 & regexm(cod2a, "[a-z]")
//replace cod2a=upper(cod2a) //2 changes
replace cod2a = rtrim(ltrim(itrim(cod2a))) //2 changes
//replace corr_KG=corr_KG+1 if record_id==12 //1 change
count if event==1 & regexm(cod2a,"NIL")|event==1 & regexm(cod2a,"ND") //47 - all correct
//list record_id ddda cod2a if event==1 & regexm(cod2a,"NIL")|event==1 & regexm(cod2a,"ND")


** onsetnumcod2a: Integer - min=0, max=99, if missing=99: FLAG 36
** (75) missing
count if event==1 & cod2a!="99" & onsetnumcod2a==. //0
//list record_id ddda cod2a onsetnumcod2a onsettxtcod2a if event==1 & cod2a!="99" & onsetnumcod2a==.
** (76) possibly invalid
count if onsetnumcod2a==999 & onsettxtcod2a!=99 //77 - all correct except 1, will correct in next check 
//list record_id ddda onsetnumcod2a onsettxtcod2a if onsetnumcod2a==999 & onsettxtcod2a!=99
count if onsetnumcod2a==99 & onsettxtcod2a==99 //1
//list record_id ddda onsetnumcod2a onsettxtcod2a if onsetnumcod2a==99 & onsettxtcod2a==99
replace flag36=flag36+1 if record_id==1209 //1 change
replace corr_KG=corr_KG+1 if record_id==1209 //1 change
replace onsetnumcod2a=999 if onsetnumcod2a==99 & onsettxtcod2a==99 //1 change


** onsettxtcod2a: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 37
** (77) missing
count if onsetnumcod2a!=. & onsettxtcod2a==. //1
//list record_id ddda onsetnumcod2a onsettxtcod2a if onsetnumcod2a!=. & onsettxtcod2a==.
replace flag37=flag37+1 if record_id==967 //1 change
replace corr_KG=corr_KG+1 if record_id==967 //1 change
replace onsettxtcod2a=99 if onsetnumcod2a!=. & onsettxtcod2a==. //1 change
count if onsetnumcod2a==999 & onsettxtcod2a==. //0
** (78) possibly invalid
count if onsetnumcod2a!=999 & onsettxtcod2a==99 //3 - all correct
//list record_id ddda duration* onsetnumcod2a onsettxtcod2a onset* if onsetnumcod2a!=999 & onsettxtcod2a==99
replace flag37=flag37+1 if onsetnumcod2a!=999 & onsettxtcod2a==99 & record_id!=859 & record_id!=1599 //1 change
replace onsettxtcod2a=3 if record_id==763


** cod2b: Text, if missing=99: FLAG 38
** (79) missing
count if event==1 & cod2b=="" //0
//list record_id ddda cod2b if event==1 & cod2b==""
** (80) invalid
count if event==1 & regexm(cod2b, "[a-z]") //0
//list record_id ddda cod2b onsetnumcod2b onsettxtcod2b if event==1 & regexm(cod2b, "[a-z]")
//replace cod2b=upper(cod2b) //0 changes
replace cod2b = rtrim(ltrim(itrim(cod2b))) //4 changes
count if event==1 & regexm(cod2b,"NIL")|event==1 & regexm(cod2b,"ND") //12 - all correct
//list record_id ddda cod2b if event==1 & regexm(cod2b,"NIL")|event==1 & regexm(cod2b,"ND")


** onsetnumcod2b: Integer - min=0, max=99, if missing=99: FLAG 39
** (81) missing
count if event==1 & cod2b!="99" & onsetnumcod2b==. //0
//list record_id ddda cod2b onsetnumcod2b onsettxtcod2b if event==1 & cod2b!="99" & onsetnumcod2b==.
** (82) possibly invalid
count if onsetnumcod2b==999 & onsettxtcod2b!=99 //33 - all correct
//list record_id ddda onsetnumcod2b onsettxtcod2b if onsetnumcod2b==999 & onsettxtcod2b!=99
count if onsetnumcod2b==99 & onsettxtcod2b==99 //0
//list record_id ddda onsetnumcod2b onsettxtcod2b if onsetnumcod2b==99 & onsettxtcod2b==99


** onsettxtcod2b: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 40
** (83) missing
count if onsetnumcod2b!=. & onsettxtcod2b==. //0
//list record_id ddda onsetnumcod2b onsettxtcod2b if onsetnumcod2b!=. & onsettxtcod2b==.
count if onsetnumcod2b==999 & onsettxtcod2b==. //0
** (84) possibly invalid
count if onsetnumcod2b!=999 & onsettxtcod2b==99 //1 - all correct
//list record_id ddda duration* onsetnumcod2b onsettxtcod2b onset* if onsetnumcod2b!=999 & onsettxtcod2b==99


** pod: Text, if missing=99: FLAG 41
** (85) missing
count if event==1 & pod=="" //0
//list record_id ddda pod if event==1 & pod==""
** (86) invalid
count if event==1 & regexm(pod, "[a-z]") //2
//list record_id ddda pod if event==1 & regexm(pod, "[a-z]")
replace pod=upper(pod) //2 changes
replace pod = rtrim(ltrim(itrim(pod))) //5 changes
count if event==1 & regexm(pod,"NIL")|event==1 & regexm(pod,"ND") //141 - all correct
//list record_id ddda pod if event==1 & regexm(pod,"NIL")|event==1 & regexm(pod,"ND")


** deathparish: FLAG 42
** (87) missing
count if event==1 & deathparish==. //0
//list record_id ddda deathparish if event==1 & deathparish==.
** (88) invalid - see district demarcations noted below:
/*	Districts are assigned based on death parish
		District A - anything below top rock christ church and st. michael 
		District B - anything above top rock christ church and st. george
		District C - st. philip and st. john
		District D - st. thomas
		District E - st. james, st. peter, st. lucy
		District F - st. joseph, st. andrew
*/
** (88) Christ Church
count if deathparish==1 & district!=1 //93 - all correct
//list record_id ddda district pod deathparish if deathparish==1 & district!=1
** (89) St Andrew
count if deathparish==2 & district!=6 //0
//list record_id ddda deathparish district pod if deathparish==2 & district!=6
** (90) St George
count if deathparish==3 & district!=2 //1 - correct district from registry (coroner case)
//list record_id ddda deathparish district pod if deathparish==3 & district!=2
** (91) St James
count if deathparish==4 & district!=5 //1
//list record_id ddda deathparish district pod if deathparish==4 & district!=5
replace flag42=flag42+1 if record_id==582 // change
replace corr_KG=corr_KG+1 if record_id==582 // change
replace deathparish=8 if record_id==582 // change
** (92) St John
count if deathparish==5 & district!=3 //1
//list record_id ddda deathparish district pod if deathparish==5 & district!=3
replace flag42=flag42+1 if record_id==254 //1 change
replace corr_KG=corr_KG+1 if record_id==254 //1 change
replace deathparish=8 if record_id==254 //1 change
** (93) St Joseph
count if deathparish==6 & district!=6 //0
//list record_id ddda deathparish district pod if deathparish==6 & district!=6
** (94) St Joseph
count if deathparish==7 & district!=5 //0
//list record_id ddda deathparish district pod if deathparish==7 & district!=5
** (95) St Michael
count if deathparish==8 & district!=1 //1
//list record_id ddda deathparish district pod if deathparish==8 & district!=1
replace flag8=flag8+1 if record_id==1776 //1 change
replace corr_intern=corr_intern+1 if record_id==1776 //1 change
replace district=1 if record_id==1776 //1 change
** (96) St Peter
count if deathparish==9 & district!=5 //2
//list record_id ddda deathparish district pod if deathparish==9 & district!=5
replace flag42=flag42+1 if record_id==23|record_id==1632 //2 changes
replace corr_AH=corr_AH+1 if record_id==23 //1 change
replace corr_intern=corr_intern+1 if record_id==1632 //1 change
replace deathparish=8 if record_id==23|record_id==1632 //2 changes
** (97) St Philip
count if deathparish==10 & district!=3 //1
//list record_id ddda deathparish district pod if deathparish==10 & district!=3
replace flag42=flag42+1 if record_id==1794 //1 change
replace corr_intern=corr_intern+1 if record_id==1794 //1 change
replace deathparish=8 if record_id==1794 //1 change
** (98) St Thomas
count if deathparish==11 & district!=4 //0
//list record_id ddda deathparish district pod if deathparish==11 & district!=4


** regdate: Y-M-D: FLAG 43
** (99) missing
count if event==1 & regdate==. //0
//list record_id ddda dod regdate if event==1 & regdate==.
** (100) invalid - future date
count if event==1 & regdate!=. & regdate>today //1
sort record_id
//list record_id ddda dod regdate pname if event==1 & regdate!=. & regdate>today
replace pname=subinstr(pname,"J","JO",.) if record_id==1789 //1 change
replace flag43=flag43+1 if record_id==1789
replace corr_intern=corr_intern+1 if record_id==1789
replace regdate=regdate-365.25 if record_id==1789 //1 change
replace flag43=flag43+1 if record_id==1789
replace corr_intern=corr_intern+1 if record_id==1789 //1 change
drop today


** certifier: Text, if missing=99: FLAG 44
** (101) missing
count if event==1 & certifier=="" //0
//list record_id ddda certifier if event==1 & certifier==""
count if certifier=="999" //1
replace flag44=flag44+1 if record_id==163 //1 change
replace corr_AH=corr_AH+1 if record_id==163 //1 change
replace certifier="99" if certifier=="999" //1 change
** (102) invalid
count if event==1 & regexm(certifier, "[a-z]") //1
//list record_id ddda certifier if event==1 & regexm(certifier, "[a-z]")
replace certifier=upper(certifier) //1 change
replace certifier = rtrim(ltrim(itrim(certifier))) //4 changes
replace flag44=flag44+1 if record_id==236 //1 change
replace corr_KG=corr_KG+1 if record_id==236 //1 change
count if event==1 & regexm(certifier,"NIL")|event==1 & regexm(certifier,"ND") //190 - all correct
//list record_id ddda certifier if event==1 & regexm(certifier,"NIL")|event==1 & regexm(certifier,"ND")


** certifieraddr: Text, if missing=99: FLAG 45
** (103) missing
count if event==1 & certifieraddr=="" //0
//list record_id ddda certifieraddr if event==1 & certifieraddr==""
** (104) invalid
count if event==1 & regexm(certifieraddr, "[a-z]") //2
//list record_id ddda certifieraddr if event==1 & regexm(certifieraddr, "[a-z]")
replace flag45=flag45+1 if event==1 & regexm(certifieraddr, "[a-z]") //2 changes
replace corr_KG=corr_KG+1 if record_id==236 //1 change
replace corr_AH=corr_AH+1 if record_id==388 //1 change
replace certifieraddr=upper(certifieraddr) //2 changes
replace certifieraddr = rtrim(ltrim(itrim(certifieraddr))) //19 changes
count if event==1 & regexm(certifieraddr,"NIL")|event==1 & regexm(certifieraddr,"ND") //57 - all correct
//list record_id ddda certifieraddr if event==1 & regexm(certifieraddr,"NIL")|event==1 & regexm(certifieraddr,"ND")


** namematch: readonly: FLAG 46
** (105) missing
count if event==1 & namematch==. //2,112 - already checked for duplicates above
replace namematch=2 if event==1 & namematch==. //2,112 changes
//list record_id ddda namematch if event==1 & namematch==.


** cleaned: 1=Yes; 2=No: FLAG 47
** (105) missing
count if event==1 & cleaned==. //2,140
replace cleaned=1 if event==1 & cleaned==. //2,140 changes


** death_certificate_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete: FLAG 48
** (106) missing
count if event==1 & recstatdc==. //0
** (107) invalid - incomplete and no reason given in field comment of redcapdb
count if event==1 & recstatdc==0 //0
//list record_id ddda dddoa recstatdc if event==1 & recstatdc==0
** (108) invalid - unverified and no reason given in field comment of redcapdb
count if event==1 & recstatdc==1 //0



*******************
** TRACKING FORM **
*******************

** tfdddoa: Y-M-D H:M, readonly: FLAG 49
** (109) missing
count if event==2 & tfdddoa==. //0


** tfddda: readonly, user logged into redcap: FLAG 50
** (110) missing
count if event==2 & tfddda==. //0
//list record_id if event==2 & tfddda==.


** tfregnumstart: integer: FLAG 51
** (111) missing
count if event==2 & tfregnumstart==. //0


** tfdistrictstart: letters only: FLAG 52
** (112) missing
count if event==2 & tfdistrictstart=="" //0
** (113) invalid
count if event==2 & regexm(tfdistrictstart, "[a-z]") //0
replace tfdistrictstart = rtrim(ltrim(itrim(tfdistrictstart))) //0 changes


** tfregnumend: integer: FLAG 53
** (114) missing
count if event==2 & tfregnumend==. //0
//list record_id tfddda tfregnumend if event==2 & tfregnumend==.


** tfdistrictend: letters only: FLAG 54
** (115) missing
count if event==2 & tfdistrictend=="" //0
//list record_id tfddda tfdistrictend if event==2 & tfdistrictend==""
** (116) invalid
count if event==2 & regexm(tfdistrictend, "[a-z]") //0
replace tfdistrictend = rtrim(ltrim(itrim(tfdistrictend))) //0 changes


** tfddtxt: FLAG 55
replace tfddtxt = rtrim(ltrim(itrim(tfddtxt))) //24 changes


** tracking_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete: FLAG 56
** (117) missing
count if event==2 & recstattf==. //0
** (118) invalid - incomplete and no reason given in field comment of redcapdb
count if event==2 & recstattf==0 //0
//list record_id tfddda tfdddoa recstattf if event==2 & recstattf==0
** (119) invalid - unverified and no reason given in field comment of redcapdb
count if event==2 & recstattf==1 //0

** REMOVE dod>2019
drop if event==1 & dodyear>2019 //1 - query for KG re 1853

** ORDER variables according to position in DeathData REDCap database
order record_id redcap_event_name event dddoa ddda odda certtype regnum district pname address parish ///
	  sex age agetxt nrnnd nrn mstatus occu durationnum durationtxt dod dodyear ///
	  cod1a onsetnumcod1a onsettxtcod1a cod1b onsetnumcod1b onsettxtcod1b ///
	  cod1c onsetnumcod1c onsettxtcod1c cod1d onsetnumcod1d onsettxtcod1d ///
	  cod2a onsetnumcod2a onsettxtcod2a cod2b onsetnumcod2b onsettxtcod2b ///
	  pod deathparish regdate certifier certifieraddr namematch cleaned recstatdc ///
	  tfdddoa tfddda tfregnumstart tfdistrictstart tfregnumend tfdistrictend tfddtxt recstattf

count //2,192

label data "BNR MORTALITY data 2008-2019"
notes _dta :These data prepared from BB national death register & BNR (Redcap) deathdata database
save "`datapath'\version02\3-output\2019_deaths_cleaned_dqi_dc" ,replace


** REMOVE variables and labels not needed in DeathData REDCap database
drop birthdate flag*
label drop _all

** REDCap will not import H:M:S format so had to change cfdate from %tcCCYY-NN-DD_HH:MM:SS to below format
format dddoa tfdddoa %tcCCYY-NN-DD_HH:MM
	  
count //2,192

label data "BNR MORTALITY data 2008-2019"
notes _dta :These data prepared from BB national death register & BNR (Redcap) deathdata database
save "`datapath'\version02\3-output\2019_deaths_cleaned_export_dc" ,replace

