** HEADER -----------------------------------------------------
**  DO-FILE METADATA
    //  algorithm name          2a_clean_deaths.do
    //  project:                BNR
    //  analysts:               Jacqueline CAMPBELL
    //  date first created      14-APR-2022
    //  date last modified      11-JAN-2023
    //  algorithm task          Clean death data
    //  status                  Completed
    //  objectve                To have one dataset with cleaned 2021 death data.
    //  note                    To combine with multi-year death dataset for unduplication purposes;
	//							Cleaned 2021 dataset to be imported into multi-year (2008-2020) death database; 
    //                          REDCap database with ALL cleaned deaths to be updated.

    
    ** General algorithm set-up
    version 17.0
    clear all
    macro drop _all
    set more off

    ** Initialising the STATA log and allow automatic page scrolling
    capture {
            program drop _all
    	drop _all
    	log close
    	}

    ** Set working directories: this is for DATASET and LOGFILE import and export
    ** DATASETS to encrypted SharePoint folder
    local datapath "X:/The University of the West Indies/DataGroup - repo_data/data_p141"
    ** LOGFILES to unencrypted OneDrive folder (.gitignore set to IGNORE log files on PUSH to GitHub)
    local logpath X:/OneDrive - The University of the West Indies/repo_datagroup/repo_p141

    ** Close any open log file and open a new log file
    capture log close
    log using "`logpath'\2a_clean_deaths_2021.smcl", replace
** HEADER -----------------------------------------------------

** JC 30jun2022+11jul2022+14jul2022+20jul2022+21jul2022+03aug2022+11jan2022: This dofile was re-run to include record_id 3232 - 3252 added by KG after completion of 2021 cleaning; Included in this process in prep for cancer annual report process

***************
** LOAD DATASET  
***************
use "`datapath'\version07\2-working\2021_deaths_prepped_dp" ,clear

count //3,112; 3231; 3233; 3236; 3242; 3243; 3245; 3246


*****************
** DATA QUALITY  
*****************
** Create quality report - corrections per DA
forvalues j=1/61 {
	gen flag`j'=0
}

label var flag1 "Record ID"
label var flag2 "Redcap Event"
label var flag3 "ABS DateTime"
label var flag4 "ABS DA"
label var flag5 "ABS Other DA"
label var flag6 "Certificate Type"
label var flag7 "ABS Reg Dept #"
label var flag8 "ABS District"
label var flag9 "Pt Name"
label var flag10 "Pt Address"
label var flag11 "Pt Parish"
label var flag12 "Sex"
label var flag13 "Age"
label var flag14 "Age (time period)"
label var flag15 "Date of Death"
label var flag16 "Death Year"
label var flag17 "NRN documented?"
label var flag18 "NRN"
label var flag19 "Marital Status"
label var flag20 "Occupation"
label var flag21 "Duration"
label var flag22 "Duration (time period)"
label var flag23 "COD 1a"
label var flag24 "Onset 1a"
label var flag25 "Onset 1a (time period)"
label var flag26 "COD 1b"
label var flag27 "Onset 1b"
label var flag28 "Onset 1b (time period)"
label var flag29 "COD 1c"
label var flag30 "Onset 1c"
label var flag31 "Onset 1c (time period)"
label var flag32 "COD 1d"
label var flag33 "Onset 1d"
label var flag34 "Onset 1d (time period)"
label var flag35 "COD 2a"
label var flag36 "Onset 2a"
label var flag37 "Onset 2a (time period)"
label var flag38 "COD 2b"
label var flag39 "Onset 2b"
label var flag40 "Onset 2b (time period)"
label var flag41 "Place of Death"
label var flag42 "Death Parish"
label var flag43 "Reg Date"
label var flag44 "Certifier"
label var flag45 "Certifer Address"
label var flag46 "Name Match"
label var flag47 "Cleaned?"
label var flag48 "ABS Complete?"
label var flag49 "TF Date Start"
label var flag50 "TF Time Start"
label var flag51 "TF DA"
label var flag52 "TF Reg # START"
label var flag53 "TF District START"
label var flag54 "TF Reg # END"
label var flag55 "TF District END"
label var flag56 "TF Date End"
label var flag57 "TF Time End"
label var flag58 "TF Time Elapsed (hrs)"
label var flag59 "TF Time Elapsed (mins)"
label var flag60 "TF Comments"
label var flag61 "TF Complete?"


gen corr_AH=0 //DA code=25
gen corr_KG=0 //DA code=04
gen corr_NR=0 //DA code=20
gen corr_KWG=0 //DA code=13
gen corr_TH=0 //DA code=14
gen corr_intern=0 //DA code=98


*****************
** DATA CLEANING  
*****************
** CLEAN each variable according to below consistency checks and the quality rules in DeathData REDCap database

************************
**  DEATH CERTIFICATE **
**        FORM        **
************************
sort record_id
** record_id (auto-generated by REDCap): FLAG 1
** (1) missing/duplicate
count if record_id==. //0
duplicates list record_id, nolabel sepby(record_id) //0 duplicates
//replace record_id=4384 if record_id==2497 & redcap_event_name=="tracking_arm_2" //1 change

** event (auto-generated by REDCap): FLAG 2
** (2) missing
count if event==. //0


** dddoa: Y-M-D H:M, readonly: FLAG 3
** (3) missing
count if event==1 & dddoa==. //0


** ddda: FLAG 4
** (4) missing
count if event==1 & ddda==. //0
count if event==1 & (ddda!=4 & ddda!=13 & ddda!=14 & ddda!=20 & ddda!=25 & ddda!=98) //0
//list record_id ddda if event==1 & (ddda!=4 & ddda!=13 & ddda!=14 & ddda!=20 & ddda!=25 & ddda!=98)
//replace flag4=flag4+1 if record_id==2475|record_id==2883
//replace corr_TH=corr_TH+1 if record_id==2475|record_id==2883


** odda: FLAG 5
** (5) missing
count if ddda==98 & odda=="" //0
//list record_id event dddoa ddda odda if ddda==98 & odda==""
//replace flag4=flag4+1 if ddda==98 & odda=="" //4 changes
//replace corr_intern=corr_intern+1 if ddda==98 & odda==""


** (6) invalid
count if ddda!=98 & odda!="" //0
//list record_id event dddoa ddda odda if ddda!=98 & odda!=""


** certtype: 1=MEDICAL 2=POST MORTEM 3=CORONER 99=ND, required: FLAG 6
** (7) missing
count if event==1 & certtype==. //0
//list record_id event dddoa ddda certtype if event==1 & certtype==.


** regnum: integer, if missing=9999: FLAG 7
** (8) missing
count if event==1 & regnum==.|event==1 & regnum==0 //0
//list record_id ddda regnum if event==1 & regnum==.|event==1 & regnum==0
** (9) invalid
count if event==1 & regnum>9999 //0
** (9) duplicate
sort regnum district
quietly by regnum district:  gen dupreg = cond(_N==1,0,_n)
sort regnum district
count if event==1 & dupreg>0  //316; 513 - different pts; Reg. Dept used same regnum for diff. pts
sort regnum pname record_id
//list record_id dddoa ddda odda pname regnum district nrn dodyear recstatdc if event==1 & dupreg>0
//list record_id pname regnum district nrn dod if event==1 & dupreg>0, nolabel sepby(regnum)
//drop if record_id== //1 deleted - the rest were previously deleted
drop dupreg


** district: 1=A 2=B 3=C 4=D 5=E 6=F: FLAG 8
** (10) missing
count if event==1 & district==. //0


** pname: Text, if missing=99: FLAG 9
** (11) missing
count if event==1 & pname=="" //0
** (12) invalid
count if event==1 & regexm(pname, "[a-z]") //0

//list record_id event ddda odda pname if event==1 & regexm(pname, "[a-z]")
//replace flag9=flag9+1 if event==1 & regexm(pname, "[a-z]") // changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(pname, "[a-z]") // changes
replace pname=upper(pname) //87 changes
count if event==1 & regexm(pname,"NIL")|event==1 & regexm(pname,"ND") //294 - all correct
//list record_id ddda odda pname if event==1 & regexm(pname,"NIL")|event==1 & regexm(pname,"ND")
count if regexm(pname, "TEST")|regexm(pname, "DUMMY") //1
drop if record_id==1491 //dummy record

** (13) duplicate
sort pname
quietly by pname:  gen dup = cond(_N==1,0,_n)
sort pname
count if event==1 & dup>0  //28 - different DAs entered same certificates
sort pname record_id
//list record_id dddoa ddda odda pname regnum district nrn if event==1 & dup>0
//list record_id pname regnum district certtype nrn dod dddoa ddda if event==1 & dup>0, nolabel sepby(pname)

replace namematch=1 if record_id==1707|record_id==3095|record_id==154|record_id==977 ///
					   |record_id==3048|record_id==3075|record_id==913|record_id==1495 ///
					   |record_id==2226|record_id==3005|record_id==1555|record_id==2401 ///
					   |record_id==60|record_id==449|record_id==1546|record_id==1741 ///
					   |record_id==883|record_id==1220|record_id==319|record_id==3076 ///
					   |record_id==18|record_id==1139|record_id==2147|record_id==2525 ///
					   |record_id==1575|record_id==2175|record_id==325|record_id==897 //28 changes
//drop if record_id==3277 //1 deleted - duplicate of record_id 528
//drop if event==1 & dup>0 & namematch==. // deleted
drop dup

/* 
Check below list for cases where namematch=no match but 
there is a pt with same name then:
 (1) check if same pt and remove duplicate pt;
 (2) check if same name but different pt and
	 update namematch variable to reflect this, i.e.
	 namematch=1
*/
gen dod2=dod
format dod2 %tdCCYY-NN-DD
tostring dod2 ,replace

sort pname dod2 record_id
quietly by pname dod2 : gen dupnmdod2 = cond(_N==1,0,_n)
sort pname dod2 record_id
count if event==1 & dupnmdod2>0 //0
drop dod2 dupnmdod2


** address: Text, if missing=99: FLAG 10
** (14) missing
count if event==1 & address=="" //0
** (15) invalid 
count if event==1 & regexm(address, "[a-z]") //0
//list record_id event ddda odda address if event==1 & regexm(address, "[a-z]")
//replace flag10=flag10+1 if event==1 & regexm(address, "[a-z]") //94 changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(address, "[a-z]") //94 changes
replace address=upper(address) //0 changes
count if event==1 & regexm(address,"NIL")|event==1 & regexm(address,"ND") //532; 554 - all correct
//list record_id ddda odda address if event==1 & regexm(address,"NIL")|event==1 & regexm(address,"ND")


** parish: FLAG 11
** (16) missing
count if event==1 & parish==. //0


** sex:	1=Male 2=Female 99=ND: FLAG 12
** (17) missing
count if event==1 & sex==. //0
//list record_id event ddda pname sex if event==1 & sex==.
** (18) invalid - female with prostate
count if sex==2 & (regexm(cod1a, "PROSTAT")|regexm(cod1b, "PROSTAT")|regexm(cod1c, "PROSTAT") ///
		|regexm(cod1d, "PROSTAT")|regexm(cod2a, "PROSTAT")|regexm(cod2b, "PROSTAT")) //1
//list record_id ddda pname nrn sex cod* if (regexm(cod1a, "PROSTAT")|regexm(cod1b, "PROSTAT")|regexm(cod1c, "PROSTAT")|regexm(cod1d, "PROSTAT")|regexm(cod2a, "PROSTAT")|regexm(cod2b, "PROSTAT")) & sex==2
recode sex 2=1 if record_id==671 //1 change
replace flag12=flag12+1 if record_id==671 //1 change
replace corr_KG=corr_KG+1 if record_id==671 //1 change
** (19) visual check - first names for those missing nrn
count if sex==1 & nrn==. //56; 60 - check if there is a stata check for this e.g. soundex,etc - 0 changes
//list record_id ddda pname sex if sex==1 & nrn==.
//recode sex 1=2 if record_id== //0 changes
//replace flag12=flag12+1 if record_id==1491 //1 change
//replace corr_KG=corr_KG+1 if record_id==1491 //1 change

** (20) invalid - male with female genital cod
count if sex==1 & (regexm(cod1a, "UTER") | regexm(cod1a, "OMA OF THE VULVA") | ///
			regexm(cod1a, "CHORIOCARCIN") | regexm(cod1a, "ENDOMETRIAL CARCINOMA") | ///
			regexm(cod1a, "ENDOMETRIAL CANC") | regexm(cod1a, "OF ENDOMETRIUM") | ///
			regexm(cod1a, "OF THE ENDOMETRIUM") | regexm(cod1a, "VULVA CARCINOMA") | ///
			regexm(cod1a, "VULVAL CANCER") | regexm(cod1a, "VAGINAL CARCINOMA")|regexm(cod1a, "ENDOMETRIUM")) //0
/*list record_id ddda pname nrn sex cod* if sex==1 & (regexm(cod1a, "UTER") | regexm(cod1a, "OMA OF THE VULVA") | ///
			regexm(cod1a, "CHORIOCARCIN") | regexm(cod1a, "ENDOMETRIAL CARCINOMA") | ///
			regexm(cod1a, "ENDOMETRIAL CANC") | regexm(cod1a, "OF ENDOMETRIUM") | ///
			regexm(cod1a, "OF THE ENDOMETRIUM") | regexm(cod1a, "VULVA CARCINOMA") | ///
			regexm(cod1a, "VULVAL CANCER") | regexm(cod1a, "VAGINAL CARCINOMA")|regexm(cod1a, "ENDOMETRIUM"))
*/
//recode sex 1=2 if record_id==70|record_id==711 //2 changes
//replace flag12=flag12+1 if record_id==70|record_id==711 //2 changes
//replace corr_KG=corr_KG+1 if record_id==70|record_id==711 //2 changes
** (21) visual check - first names for those missing nrn
count if sex==2 & nrn==. //47; 49 - check if there is a stata check for this e.g. soundex,etc - 0 changes
//list record_id ddda pname sex if sex==2 & nrn==.
recode sex 2=1 if record_id==2796 //1 change
replace flag12=flag12+1 if record_id==2796 //1 change
replace corr_KG=corr_KG+1 if record_id==2796 //1 change


** age: Integer - min=0, max=999: FLAG 13
** (22) missing
count if event==1 & age==. //0; 1
drop if record_id==3113 //half info is missing in this record JC emailed KG on 29jun2022 for clarification as no comments documented for this record
** (23) missing - NRN not missing
count if (age==.|age==0) & nrn!=. //0


** agetxt - 1 "Minutes" 2 "Hours" 3 "Days" 4 "Weeks" 5 "Months" 6 "Years" 99 "ND": FLAG 14
** (25) missing
count if age!=. & agetxt==. //0
** (26) invalid
count if age==999 & agetxt!=99 //0
** (27) visual check - NRN vs agetxt
count if nrn!=. & age!=. & agetxt!=6 //5 - 4 correct
//list record_id ddda odda dod nrn age agetxt if nrn!=. & age!=. & agetxt!=6 //checked these using redcap db & electoral list
replace agetxt=6 if record_id==1516 //1 change
replace flag14=flag14+1 if record_id==1516 //1 change
replace corr_KG=corr_KG+1 if record_id==1516 //1 change


** dod: Y-M-D (need to clean dod before other checks): FLAG 15
** (28) missing
count if event==1 & dod==. //0
** (29) invalid - future date
gen currentd=c(current_date)
gen double today=date(currentd, "DMY")
drop currentd
format today %tdCCYY-NN-DD
count if event==1 & dod>today //0
sort record_id
//list record_id ddda dod regdate pname if event==1 & dod>today
** (30) invalid - after reg date
count if event==1 & dod>regdate //11 (check redcapdb for if any coroner cases; 2019 TF redcap report for 'true' 2019 cases)
list record_id dddoa ddda odda certtype dod regdate pname if event==1 & dod>regdate
replace flag15=flag15+1 if event==1 & dod>regdate
replace corr_AH=corr_AH+1 if record_id==3|record_id==35 //2 changes
replace corr_KG=corr_KG+1 if event==1 & dod>regdate & record_id!=3 & record_id!=35 //9 changes
replace regdate=regdate+365 if record_id==1253|record_id==2856 //2 changes
replace dod=dod-273 if record_id==35 //1 change
replace regdate=regdate+366 if event==1 & dod>regdate & year(regdate)==2020 //2 changes
//swapval regdate dod if dod>regdate //ssc install swapval - doesn't work for dates, only for numeric or string values
gen dod2=regdate if dod>regdate
gen regdate2=dod if dod>regdate
format dod2 regdate2 %tdCCYY-NN-DD
replace dod=dod2 if dod2!=. //0; 6 changes
replace regdate=regdate2 if regdate2!=. //0; 6 changes
drop dod2 regdate2


** dodyear (not included in single year Redcap db but done for multi-year Redcap db): FLAG 16
** (31) missing
count if event==1 & dodyear==. //0
//list record_id ddda dod regdate if event==1 & dodyear==.
** (32) invalid - deaths before/after 2019
count if event==1 & dodyear!=2021 //3 - 2020 deaths that were collected after 2020 was cleaned so missing from multi-year db
//list record_id dddoa ddda odda dod dodyear pname nrn regdate if event==1 & dodyear!=2021
//keep these 3 records from 2020 to be included in multi-year db.
//tab dodyear if event==1,m
/*
    Year of |
      Death |      Freq.     Percent        Cum.
------------+-----------------------------------
       2020 |          3        0.10        0.10
       2021 |      3,011       99.90      100.00
------------+-----------------------------------
      Total |      3,014      100.00
*/
//drop if event==1 & dodyear>2020 //0 deleted

** nrnnd: 1=Yes 2=No: FLAG 17
** (33) missing
count if event==1 & nrnnd==. //0
//list record_id ddda nrn if event==1 & nrnnd==.
** (34) invalid
count if event==1 & nrn==. & nrnnd==1 //0
//list record_id ddda pname nrn nrnnd if event==1 & nrn==. & nrnnd==1
//replace flag17=flag17+1 if record_id==2386 //1 change
//replace corr_TH=corr_TH+1 if record_id==2386 //1 change
/*
preserve
clear
import excel using "`datapath'\version07\1-input\NRN_20200909.xlsx" , firstrow case(lower)
save "`datapath'\version07\2-working\2020_deaths_nrn" ,replace
restore
merge 1:1 record_id using "`datapath'\version07\2-working\2020_deaths_nrn" ,force
destring elec_nrn ,replace
format elec_nrn %15.0g
replace nrn=elec_nrn if record_id==2386 //1 change
drop elec_* _merge
*/

** (35) invalid
count if nrn!=. & nrnnd==2 //0
//list record_id ddda odda pname nrn nrnnd if nrn!=. & nrnnd==2
//replace flag17=flag17+1 if nrn!=. & nrnnd==2 //2 changes
//replace corr_intern=corr_intern+1 if nrn!=. & nrnnd==2 //2 changes
replace nrnnd=1 if nrn!=. & nrnnd==2 //0 changes

** nrn: dob-####, partial missing=dob-9999, if missing=.: FLAG 18
tostring nrn, gen(natregno) format("%15.0f")
replace natregno="" if natregno=="." //187; 206 changes
** (36) missing
count if event==1 & nrnnd==1 & (natregno==""|natregno=="9999999999") //0
** (37) invalid - length (checked against electoral list; no error for DA if leading zero was in redcap db)
count if natregno!="" & length(natregno)!=10 //40
//list record_id ddda odda pname age nrn natregno addr if natregno!="" & length(natregno)!=10
replace flag18=flag18+1 if natregno!="" & length(natregno)!=10 //40 changes
** Missing leading zeros not counted as DA's error - exported data as .csv
//replace corr_intern=corr_intern+1 if natregno!="" & length(natregno)!=10 & ddda==98 //9 changes
//replace corr_AH=corr_AH+1 if record_id==2815|record_id==3876|record_id==4256 //3 changes
replace corr_KG=corr_KG+1 if record_id==993|record_id==1220|record_id==1455|record_id==2132|record_id==2877 ///
							|record_id==213|record_id==221|record_id==343|record_id==1410|record_id==1510 ///
							|record_id==1764|record_id==1821|record_id==1841|record_id==1979|record_id==1981 ///
							|record_id==2022|record_id==2235|record_id==2706|record_id==2800|record_id==2854 ///
							|record_id==2975|record_id==3028|record_id==3093 //23 changes

replace natregno=subinstr(natregno,"06","6",.) if record_id==993 //1 change
replace natregno=subinstr(natregno,"31","3",.) if record_id==1220 //1 change
replace natregno=subinstr(natregno,"01","1",.) if record_id==1455 //1 change
replace natregno=subinstr(natregno,"21","1",.) if record_id==2132 //1 change

replace nrnnd=2 if record_id==2877
replace nrn=. if record_id==2877
replace natregno="" if record_id==2877

replace nrnnd=2 if record_id==1011
replace nrn=. if record_id==1011
replace natregno="" if record_id==1011

replace nrnnd=2 if record_id==2623
replace nrn=. if record_id==2623
replace natregno="" if record_id==2623

replace natregno="000" + natregno if natregno!="" & length(natregno)==7 & age<25 //2 changes
replace natregno="00" + natregno if natregno!="" & length(natregno)==8 & age<25 //0 changes
replace natregno="0" + natregno if natregno!="" & length(natregno)==9 & age<25 //13 changes
//list record_id ddda odda pname age nrn natregno addr if natregno!="" & length(natregno)!=10

replace natregno=subinstr(natregno,"8","80",.) if record_id==213 //1 change
replace natregno=subinstr(natregno,"40","400",.) if record_id==221 //1 change
replace natregno=subinstr(natregno,"99","909",.) if record_id==343 //1 change
replace natregno=subinstr(natregno,"02","022",.) if record_id==1410 //1 change
replace natregno=subinstr(natregno,"01","011",.) if record_id==1510 //1 change
replace natregno=subinstr(natregno,"61","061",.) if record_id==1764 //1 change
replace natregno=subinstr(natregno,"7","17",.) if record_id==1821 //1 change
replace natregno=subinstr(natregno,"2","7",.) if record_id==1821 //1 change
replace natregno=subinstr(natregno,"5","57",.) if record_id==1841 //1 change
replace natregno=subinstr(natregno,"5","15",.) if record_id==1981 //1 change
replace natregno=subinstr(natregno,"1","14",.) if record_id==2022 //1 change
replace natregno=subinstr(natregno,"7","77",.) if record_id==2706 //1 change
replace natregno=subinstr(natregno,"3","31",.) if record_id==2800 //1 change
replace natregno=subinstr(natregno,"5","50",.) if record_id==2854 //1 change
replace natregno=subinstr(natregno,"9","09",.) if record_id==2975 //1 change
replace natregno=subinstr(natregno,"8","82",.) if record_id==3093 //1 change

replace natregno=natregno+"2" if record_id==3028  //1 change


replace natregno=subinstr(natregno,"00", substr(subinstr(natregno,"20","",.),9,1),1) if record_id==1979  //1 change
replace natregno=natregno+"20" if record_id==1979  //1 change

** Use formatted electoral dataset to correct these NRNs
preserve
use "`datapath'\version07\2-working\2019_electoral_prepped_dp" ,clear
gen record_id=2235 if elec_id==195429
drop if record_id!=2235
keep record_id elec_nrn
save "`datapath'\version07\2-working\temp" ,replace
restore

merge 1:1 record_id using "`datapath'\version07\2-working\temp"
erase "`datapath'\version07\2-working\temp.dta"
replace natregno=elec_nrn if record_id==2235 //1 change
drop elec_* _merge

count if natregno!="" & length(natregno)!=10
count //3,111; 3229; 3231


** (38) invalid - dob but missing nrn #
count if regexm(natregno,"9999")|regexm(natregno,"99") //19; 20 - all correct (checked against electoral list)
//list record_id ddda odda age natregno pname if regexm(natregno,"9999")|regexm(natregno,"99")
//replace flag18=flag18+1 if record_id== //7 changes
** (39) invalid - female with 'male' NRN
count if sex==2 & (regex(substr(natregno,-2,1), "[1,3,5,7,9]")) & !(strmatch(strupper(natregno), "*-9999*")) //7 - checked against electoral list
//list record_id ddda odda pname natregno sex cod* if sex==2 & (regex(substr(natregno,-2,1), "[1,3,5,7,9]")) & !(strmatch(strupper(natregno), "*-9999*"))
recode sex 2=1 if record_id==38|record_id==1051|record_id==2346|record_id==2372|record_id==2579|record_id==2845 //6 changes
replace flag12=flag12+1 if record_id==38|record_id==1051|record_id==2346|record_id==2372|record_id==2579|record_id==2845 //6 changes
replace corr_KG=corr_KG+1 if record_id==1051|record_id==2346|record_id==2372|record_id==2579|record_id==2845 //5 changes
replace corr_AH=corr_AH+1 if record_id==38 //1 change

** (40) invalid - male with 'female' NRN
count if sex==1 & regex(substr(natregno,-2,1), "[0,2,4,6,8]") //8 - checked against electoral list
//list record_id ddda odda pname natregno sex cod* if sex==1 & regex(substr(natregno,-2,1), "[0,2,4,6,8]")
recode sex 1=2 if record_id==199|record_id==616|record_id==924|record_id==2424|record_id==2593|record_id==2975 //6 changes
replace flag12=flag12+1 if record_id==199|record_id==616|record_id==924|record_id==2424|record_id==2593|record_id==2975 //6 changes
replace corr_KG=corr_KG+1 if record_id==199|record_id==616|record_id==924|record_id==2424|record_id==2593|record_id==2975 //6 changes
** (41) invalid - age vs dob(nrn)
gen dobyr=substr(natregno, 1, 2) if natregno!=""
gen dobmon=substr(natregno, 3, 2) if natregno!=""
gen dobday=substr(natregno, 5, 2) if natregno!=""
count if (agetxt!=6 & natregno!="")|regex(substr(dobyr,1,1),"[0]") //19
//list record_id pname age agetxt dod natregno dobyr dobmon dobday if (agetxt!=6 & natregno!="")|regex(substr(dobyr,1,1),"[0]")
//replace dobyr="19"+dobyr if record_id==|record_id== //2 changes
replace dobyr="20"+dobyr if (agetxt!=6 & natregno!="")|regex(substr(dobyr,1,1),"[0]") //19 changes
replace dobyr="19"+dobyr if length(dobyr)==2 //2889 changes
count if length(dobyr)>4 //0
count if dobday!="" & (dobday!="01"&dobday!="02"&dobday!="03"&dobday!="04"&dobday!="05"&dobday!="06"&dobday!="07"&dobday!="08"&dobday!="09"&dobday!="10"&dobday!="11"&dobday!="12" ///
		 &dobday!="13"&dobday!="14"&dobday!="15"&dobday!="16"&dobday!="17"&dobday!="18"&dobday!="19"&dobday!="20"&dobday!="21"&dobday!="22"&dobday!="23"&dobday!="24"&dobday!="25" ///
		 &dobday!="26"&dobday!="27"&dobday!="28"&dobday!="29"&dobday!="30"&dobday!="31") //0
/*list record_id ddda dobday natregno pname if dobday!="" & (dobday!="01"&dobday!="02"&dobday!="03"&dobday!="04"&dobday!="05"&dobday!="06"&dobday!="07"&dobday!="08"&dobday!="09"&dobday!="10"&dobday!="11"&dobday!="12" ///
		 &dobday!="13"&dobday!="14"&dobday!="15"&dobday!="16"&dobday!="17"&dobday!="18"&dobday!="19"&dobday!="20"&dobday!="21"&dobday!="22"&dobday!="23"&dobday!="24"&dobday!="25" ///
		 &dobday!="26"&dobday!="27"&dobday!="28"&dobday!="29"&dobday!="30"&dobday!="31")
*/
/*
replace dobday="23" if record_id==339 //1 change
replace natregno=subinstr(natregno,"33","23",.) if record_id==339 //1 change
replace flag18=flag18+1 if record_id==339 //1 change
replace corr_intern=corr_intern+1 if record_id==339 //1 change
replace dobday="14" if record_id==4191 //1 change
replace natregno=subinstr(natregno,"41","14",.) if record_id==4191 //1 change
replace flag18=flag18+1 if record_id==4191 //1 change
replace corr_AH=corr_AH+1 if record_id==4191 //1 change
*/

count if dobmon!="" & (dobmon!="01"&dobmon!="02"&dobmon!="03"&dobmon!="04"&dobmon!="05"&dobmon!="06"&dobmon!="07"&dobmon!="08"&dobmon!="09"&dobmon!="10"&dobmon!="11"&dobmon!="12") //2
//list record_id ddda dobmon natregno pname addr if dobmon!="" & (dobmon!="01"&dobmon!="02"&dobmon!="03"&dobmon!="04"&dobmon!="05"&dobmon!="06"&dobmon!="07"&dobmon!="08"&dobmon!="09"&dobmon!="10"&dobmon!="11"&dobmon!="12")
replace natregno=subinstr(natregno,"09","90",.) if record_id==2322 //1 change
replace dobmon=subinstr(dobmon,"9","0",.) if record_id==2322 //1 change
replace natregno=subinstr(natregno,"02","92",.) if record_id==2855 //1 change
replace dobmon="09" if record_id==2855 //1 change
replace flag18=flag18+1 if record_id==2322|record_id==2855 //2 changes
replace corr_KG=corr_KG+1 if record_id==2322|record_id==2855 //2 changes

gen birthdate=dobyr+dobmon+dobday
gen dob=date(birthdate, "YMD")
format dob %tdCCYY-NN-DD
gen age2=int((dod - dob)/365.25) //now use this to assign missing age
count if age!=age2 & natregno!="" & dob!=. //60; 62
sort record_id
list record_id pname age age2 agetxt dod dob natregno if age!=age2 & natregno!=""
//replace age=95 if record_id==7 //1 change
//replace agetxt=6 if record_id==7 //1 change
replace dob=dob+36525 if record_id==2297|record_id==1714|record_id==1197|record_id==311|record_id==282 //5 changes
replace age=age2 if age!=age2 & natregno!="" & dob!=. & agetxt==6 & record_id!=2297 & record_id!=1714 & record_id!=1197 & record_id!=311 & record_id!=282 //52; 53 changes
//replace corr_NR=corr_NR+1 if record_id==7 //1 change
drop nrn dob dobday dobmon dobyr age2
rename natregno nrn


** mstatus: 1=Single 2=Married 3=Separated/Divorced 4=Widowed/Widow/Widower 99=ND: FLAG 19
** (42) missing
count if event==1 & mstatus==. //0


** occu: Text, if missing=99: FLAG 20
** (43) missing
count if event==1 & occu=="" //0
** (44) invalid 
count if event==1 & regexm(occu, "[a-z]") //0
//list record_id ddda odda occu if event==1 & regexm(occu, "[a-z]")
replace flag20=flag20+1 if event==1 & regexm(occu, "[a-z]") //0 changes
replace corr_intern=corr_intern+1 if event==1 & regexm(occu, "[a-z]")
replace occu=upper(occu) //0 changes
replace occu = rtrim(ltrim(itrim(occu))) //100 changes
count if event==1 & regexm(occu,"NIL")|event==1 & regexm(occu,"ND") //141
//list record_id ddda odda occu if event==1 & regexm(occu,"NIL")|event==1 & regexm(occu,"ND")
count if event==1 & occu=="NIL"|event==1 & occu=="ND" //0
//list record_id ddda odda occu if event==1 & occu=="NIL"|event==1 & occu=="ND"
replace flag20=flag20+1 if event==1 & occu=="NIL"|event==1 & occu=="ND" //0 changes
//replace corr_intern=corr_intern+1 if event==1 & ddda==98 & occu=="NIL"|event==1 & occu=="ND" //15 changes
//replace corr_AH=corr_AH+1 if event==1 & ddda==25 & occu=="NIL"|event==1 & occu=="ND" //8 changes
replace occu="99" if event==1 & occu=="NIL"|event==1 & occu=="ND" //0 changes


** JC 14apr2022: REVIEW COMMENT FIELD LOG FOR KG's CORRECTIONS TO THE BELOW + ONSET-INTERVAL FIELDS
** durationnum: Integer - min=0, max=99, if missing=99: FLAG 21
** (45) missing
count if event==1 & durationnum==. //0
** (46) invalid
count if durationnum==999 & durationtxt!=. & durationtxt!=99 //0
//list record_id ddda durationnum durationtxt if durationnum==999 & durationtxt!=. & durationtxt!=99
replace flag21=flag21+1 if durationnum==999 & durationtxt!=. & durationtxt!=99 //0 changes
replace durationtxt=99 if durationnum==999 & durationtxt!=. & durationtxt!=99 //0 changes
count if durationnum==99 & durationtxt==99 //0
//list record_id ddda durationnum durationtxt if durationnum==99 & durationtxt==99
//replace corr_TH=corr_TH+1 if record_id==2276
//replace corr_intern=corr_intern+1 if record_id==52|record_id==61|record_id==438
replace durationnum=999 if durationnum==99 & durationtxt==99 //0 changes


** durationtxt - 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 22
** (47) missing
count if durationnum!=. & durationnum!=999 & durationtxt==. //0
//list record_id ddda durationnum durationtxt if durationnum!=. & durationtxt==.
** (48) possibly invalid
count if durationnum!=999 & durationtxt==99 //0
//list record_id ddda durationnum durationtxt onset* if durationnum!=999 & durationtxt==99
//replace flag22=flag22+1 if record_id==351 //1 change
//replace durationtxt=4 if record_id==351 //1 change
count if durationnum==999 & durationtxt==99 //0
replace durationtxt=. if durationnum==999 & durationtxt==99 //0 changes


** cod1a: Text, if missing=99: FLAG 23
** (49) missing
count if event==1 & cod1a=="" //1
replace cod1a="99" if record_id==2796 //KG indicated in comments that this person had no medical certificate of death; Emailed NS,SF cc KG to ask if to change to 99 for all CODs or if KG should follow-up at Death Registry for an update.
replace cod1b="99" if record_id==2796
replace cod1c="99" if record_id==2796
replace cod1d="99" if record_id==2796
replace cod2a="99" if record_id==2796
replace cod2b="99" if record_id==2796
** (50) invalid
count if event==1 & regexm(cod1a, "[a-z]") //0
//list record_id ddda cod1a onsetnumcod1a onsettxtcod1a if event==1 & regexm(cod1a, "[a-z]")
replace flag23=flag23+1 if event==1 & regexm(cod1a, "[a-z]") //0 changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(cod1a, "[a-z]")
replace cod1a=upper(cod1a) //0 changes
replace cod1a = rtrim(ltrim(itrim(cod1a))) //641 changes
count if event==1 & regexm(cod1a,"NIL")|event==1 & regexm(cod1a,"ND") //259 - all correct
//list record_id ddda cod1a if event==1 & regexm(cod1a,"NIL")|event==1 & regexm(cod1a,"ND")


** onsetnumcod1a: Integer - min=0, max=99, if missing=99: FLAG 24
** (51) missing
count if event==1 & cod1a!="99" & onsetnumcod1a==. //0
** (52) possibly invalid
count if onsetnumcod1a==999 & onsettxtcod1a!=. & onsettxtcod1a!=99 //0
//list record_id ddda onsetnumcod1a onsettxtcod1a if onsetnumcod1a==999 & onsettxtcod1a!=. & onsettxtcod1a!=99
replace flag24=flag24+1 if onsetnumcod1a==999 & onsettxtcod1a!=. & onsettxtcod1a!=99 //0 changes
replace onsetnumcod1a=99 if onsetnumcod1a==999 & onsettxtcod1a!=. & onsettxtcod1a!=99 //0 changes
count if onsetnumcod1a==99 & onsettxtcod1a==99 //0
//list record_id ddda onsetnumcod1a onsettxtcod1a if onsetnumcod1a==99 & onsettxtcod1a==99
replace flag24=flag24+1 if onsetnumcod1a==99 & onsettxtcod1a==99 //0 changes
//replace corr_KG=corr_KG+1 if record_id==2425 //1 change
replace onsetnumcod1a=999 if onsetnumcod1a==99 & onsettxtcod1a==99 //0 changes


** onsettxtcod1a: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 25
** (53) missing
count if onsetnumcod1a!=. & onsetnumcod1a!=999 & onsettxtcod1a==. //0
//list record_id ddda onsetnumcod1a onsettxtcod1a if onsetnumcod1a!=. & onsetnumcod1a!=999 & onsettxtcod1a==.
** (54) possibly invalid
count if onsetnumcod1a!=999 & onsettxtcod1a==99 //3 - correct
//list record_id ddda duration* onsetnumcod1a onsettxtcod1a if onsetnumcod1a!=999 & onsettxtcod1a==99
//replace flag25=flag25+1 if onsetnumcod1a!=999 & onsettxtcod1a==99 //1 change
//replace onsetnumcod1a=999 if record_id==61
//replace corr_intern=corr_intern+1 if record_id==61
count if onsetnumcod1a==999 & onsettxtcod1a==99 //0
replace onsettxtcod1a=. if onsetnumcod1a==999 & onsettxtcod1a==99 //0 changes


** cod1b: Text, if missing=99: FLAG 26
** (55) missing
count if event==1 & cod1b=="" //0
** (56) invalid
count if event==1 & regexm(cod1b, "[a-z]") //1
//list record_id ddda odda cod1b onsetnumcod1b onsettxtcod1b if event==1 & regexm(cod1b, "[a-z]")
replace flag26=flag26+1 if event==1 & regexm(cod1b, "[a-z]") //1 change
replace corr_KG=corr_KG+1 if event==1 & regexm(cod1b, "[a-z]")
replace cod1b=subinstr(cod1b,"is","",.) if record_id==2351 //1 change
replace cod1b=upper(cod1b) //0 changes
replace cod1b = rtrim(ltrim(itrim(cod1b))) //484 changes
count if event==1 & regexm(cod1b,"NIL")|event==1 & regexm(cod1b,"ND") //150 - all correct
//list record_id ddda cod1b if event==1 & regexm(cod1b,"NIL")|event==1 & regexm(cod1b,"ND")


** onsetnumcod1b: Integer - min=0, max=99, if missing=99: FLAG 27
** (57) missing
count if event==1 & cod1b!="99" & onsetnumcod1b==. //0
//list record_id ddda cod1b onsetnumcod1b onsettxtcod1b if event==1 & cod1b!="99" & onsetnumcod1b==.
//replace flag27=flag27+1 if event==1 & cod1b!="99" & onsetnumcod1b==. //2 changes
//replace corr_intern=corr_intern+1 if event==1 & cod1b!="99" & onsetnumcod1b==.
//replace onsetnumcod1b=999 if event==1 & cod1b!="99" & onsetnumcod1b==. //2 changes
** (58) possibly invalid
count if onsetnumcod1b==999 & onsettxtcod1b!=. & onsettxtcod1b!=99 //0
//list record_id ddda onsetnumcod1b onsettxtcod1b if onsetnumcod1b==999 & onsettxtcod1b!=. & onsettxtcod1b!=99
replace flag27=flag27+1 if onsetnumcod1b==999 & onsettxtcod1b!=. & onsettxtcod1b!=99 //0 changes
replace onsetnumcod1b=99 if onsetnumcod1b==999 & onsettxtcod1b!=. & onsettxtcod1b!=99 //0 changes
count if onsetnumcod1b==99 & onsettxtcod1b==99 //0
//list record_id ddda onsetnumcod1b onsettxtcod1b if onsetnumcod1b==99 & onsettxtcod1b==99
//replace flag27=flag27+1 if record_id==2281|record_id==2425 //2 changes
//replace corr_KG=corr_KG+1 if record_id==2281 //1 change
//replace onsetnumcod1b=999 if record_id==2281|record_id==2425 //2 changes


** onsettxtcod1b: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 28
** (59) missing
count if onsetnumcod1b!=. & onsetnumcod1b!=999 & onsettxtcod1b==. //1
//list record_id ddda onsetnumcod1b onsettxtcod1b if onsetnumcod1b!=. & onsetnumcod1b!=999 & onsettxtcod1b==.
replace flag28=flag28+1 if onsetnumcod1b!=. & onsetnumcod1b!=999 & onsettxtcod1b==. //1 change
replace corr_KG=corr_KG+1 if onsetnumcod1b!=. & onsetnumcod1b!=999 & onsettxtcod1b==. //1 change
replace onsetnumcod1b=999 if record_id==1211 //1 change
** (60) possibly invalid
count if onsetnumcod1b!=999 & onsettxtcod1b==99 //2 - correct
//list record_id ddda duration* onsetnumcod1b onsettxtcod1b if onsetnumcod1b!=999 & onsettxtcod1b==99
//replace flag28=flag28+1 if onsetnumcod1b!=999 & onsettxtcod1b==99 //74 changes
//replace onsetnumcod1b=999 if onsetnumcod1b!=999 & onsettxtcod1b==99 //74 changes
count if onsetnumcod1b==999 & onsettxtcod1b==99 //0
replace onsettxtcod1b=. if onsetnumcod1b==999 & onsettxtcod1b==99 //0 changes


** cod1c: Text, if missing=99: FLAG 29
** (61) missing
count if event==1 & cod1c=="" //0
** (62) invalid
count if event==1 & regexm(cod1c, "[a-z]") //0
//list record_id ddda cod1c onsetnumcod1c onsettxtcod1c if event==1 & regexm(cod1c, "[a-z]")
replace flag29=flag29+1 if event==1 & regexm(cod1c, "[a-z]") //0 changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(cod1c, "[a-z]")
replace cod1c=upper(cod1c) //0 changes
replace cod1c = rtrim(ltrim(itrim(cod1c))) //167 changes
count if event==1 & regexm(cod1c,"NIL")|event==1 & regexm(cod1c,"ND") //53 - all correct
//list record_id ddda cod1c if event==1 & regexm(cod1c,"NIL")|event==1 & regexm(cod1c,"ND")


** onsetnumcod1c: Integer - min=0, max=99, if missing=99: FLAG 30
** (63) missing
count if event==1 & cod1c!="99" & onsetnumcod1c==. //0
//list record_id ddda cod1c onsetnumcod1c onsettxtcod1c if event==1 & cod1c!="99" & onsetnumcod1c==.
//replace flag30=flag30+1 if event==1 & cod1c!="99" & onsetnumcod1c==. //1 change
//replace corr_intern=corr_intern+1 if event==1 & cod1c!="99" & onsetnumcod1c==.
//replace onsetnumcod1c=999 if event==1 & cod1c!="99" & onsetnumcod1c==. //1 change
** (64) possibly invalid
count if onsetnumcod1c==999 & onsettxtcod1c!=. & onsettxtcod1c!=99 //0
//list record_id ddda onsetnumcod1c onsettxtcod1c if onsetnumcod1c==999 & onsettxtcod1c!=. & onsettxtcod1c!=99
replace flag30=flag30+1 if onsetnumcod1c==999 & onsettxtcod1c!=. & onsettxtcod1c!=99 //0 changes
replace onsetnumcod1c=99 if onsetnumcod1c==999 & onsettxtcod1c!=. & onsettxtcod1c!=99 //0 changes
count if onsetnumcod1c==99 & onsettxtcod1c==99 //0
//list record_id ddda onsetnumcod1c onsettxtcod1c if onsetnumcod1c==99 & onsettxtcod1c==99
//replace flag30=flag30+1 if record_id==64
//replace corr_intern=corr_intern+1 if record_id==64
//replace onsetnumcod1c=999 if record_id==64


** onsettxtcod1c: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 31
** (65) missing
count if onsetnumcod1c!=. & onsetnumcod1c!=999 & onsettxtcod1c==. //0
//list record_id ddda onsetnumcod1c onsettxtcod1c if onsetnumcod1c!=. & onsettxtcod1c==.
** (66) possibly invalid
count if onsetnumcod1c!=999 & onsettxtcod1c==99 //2 - correct
//list record_id ddda duration* onsetnumcod1c onsettxtcod1c if onsetnumcod1c!=999 & onsettxtcod1c==99
//replace flag28=flag28+1 if onsetnumcod1c!=999 & onsettxtcod1c==99 //128 changes
//replace onsetnumcod1c=999 if onsetnumcod1c!=999 & onsettxtcod1c==99 //128 changes
count if onsetnumcod1c==999 & onsettxtcod1c==99 //0
replace onsettxtcod1c=. if onsetnumcod1c==999 & onsettxtcod1c==99 //0 changes


** cod1d: Text, if missing=99: FLAG 32
** (67) missing
count if event==1 & cod1d=="" //0
//list record_id ddda cod1d if event==1 & cod1d==""
** (68) invalid
count if event==1 & regexm(cod1d, "[a-z]") //0
//list record_id ddda cod1d onsetnumcod1d onsettxtcod1d if event==1 & regexm(cod1d, "[a-z]")
replace flag32=flag32+1 if event==1 & regexm(cod1d, "[a-z]") //0 changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(cod1d, "[a-z]")
replace cod1d=upper(cod1d) //0 changes
replace cod1d = rtrim(ltrim(itrim(cod1d))) //51 changes
count if event==1 & regexm(cod1d,"NIL")|event==1 & regexm(cod1d,"ND") //14 - all correct
//list record_id ddda cod1d if event==1 & regexm(cod1d,"NIL")|event==1 & regexm(cod1d,"ND")


** onsetnumcod1d: Integer - min=0, max=99, if missing=99: FLAG 33
** (69) missing
count if event==1 & cod1d!="99" & onsetnumcod1d==. //0
//list record_id ddda cod1d onsetnumcod1d onsettxtcod1d if event==1 & cod1d!="99" & onsetnumcod1d==.
** (70) possibly invalid
count if onsetnumcod1d==999 & onsettxtcod1d!=. & onsettxtcod1d!=99 //0
//list record_id ddda onsetnumcod1d onsettxtcod1d if onsetnumcod1d==999 & onsettxtcod1d!=. & onsettxtcod1d!=99
replace flag33=flag33+1 if onsetnumcod1d==999 & onsettxtcod1d!=. & onsettxtcod1d!=99 //0 changes
replace onsetnumcod1d=99 if onsetnumcod1d==999 & onsettxtcod1d!=. & onsettxtcod1d!=99 //0 changes
count if onsetnumcod1d==99 & onsettxtcod1d==99 //0
//list record_id ddda onsetnumcod1d onsettxtcod1d if onsetnumcod1d==99 & onsettxtcod1d==99
//replace corr_intern=corr_intern+1 if record_id==2273
//replace corr_KG=corr_KG+1 if record_id==2304


** onsettxtcod1d: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 34
** (71) missing
count if onsetnumcod1d!=. & onsetnumcod1d!=999 & onsettxtcod1d==. //0
//list record_id ddda onsetnumcod1d onsettxtcod1d if onsetnumcod1d!=. & onsetnumcod1d!=999 & onsettxtcod1d==.
//replace flag34=flag34+1 if onsetnumcod1d!=. & onsetnumcod1d!=999 & onsettxtcod1d==. //1 change
** (72) possibly invalid
count if onsetnumcod1d!=999 & onsettxtcod1d==99 //1 - correct
//list record_id ddda duration* onsetnumcod1d onsettxtcod1d if onsetnumcod1d!=999 & onsettxtcod1d==99
//replace flag34=flag34+1 if onsetnumcod1d!=999 & onsettxtcod1d==99 //150 changes
//replace onsetnumcod1d=999 if onsetnumcod1d!=999 & onsettxtcod1d==99 //150 changes
count if onsetnumcod1d==999 & onsettxtcod1d==99 //0
replace onsettxtcod1d=. if onsetnumcod1d==999 & onsettxtcod1d==99 //0 changes


** cod2a: Text, if missing=99: FLAG 35
** (73) missing
count if event==1 & cod2a=="" //0
//list record_id ddda cod2a if event==1 & cod2a==""
** (74) invalid
count if event==1 & regexm(cod2a, "[a-z]") //0
//list record_id ddda cod2a onsetnumcod2a onsettxtcod2a if event==1 & regexm(cod2a, "[a-z]")
replace flag35=flag35+1 if event==1 & regexm(cod2a, "[a-z]") //29 changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(cod2a, "[a-z]")
replace cod2a=upper(cod2a) //29 changes
replace cod2a = rtrim(ltrim(itrim(cod2a))) //487 changes
//replace corr_KG=corr_KG+1 if record_id==12 //1 change
count if event==1 & regexm(cod2a,"NIL")|event==1 & regexm(cod2a,"ND") //71 - all correct
//list record_id ddda cod2a if event==1 & regexm(cod2a,"NIL")|event==1 & regexm(cod2a,"ND")


** onsetnumcod2a: Integer - min=0, max=99, if missing=99: FLAG 36
** (75) missing
count if event==1 & cod2a!="99" & onsetnumcod2a==. //0
//list record_id ddda cod2a onsetnumcod2a onsettxtcod2a if event==1 & cod2a!="99" & onsetnumcod2a==.
//replace flag36=flag36+1 if event==1 & cod2a!="99" & onsetnumcod2a==. //1 change
//replace corr_intern=corr_intern+1 if event==1 & cod2a!="99" & onsetnumcod2a==.
//replace onsetnumcod2a=999 if event==1 & cod2a!="99" & onsetnumcod2a==. //1 change
** (76) possibly invalid
count if onsetnumcod2a==999 & onsettxtcod2a!=. & onsettxtcod2a!=99 //0
//list record_id ddda onsetnumcod2a onsettxtcod2a if onsetnumcod2a==999 & onsettxtcod2a!=. & onsettxtcod2a!=99
replace flag36=flag36+1 if onsetnumcod2a==999 & onsettxtcod2a!=. & onsettxtcod2a!=99 //0 changes
//replace onsetnumcod2a=99 if onsetnumcod2a==999 & onsettxtcod2a!=. & onsettxtcod2a!=99 //55 changes
count if onsetnumcod2a==99 & onsettxtcod2a==99 //0
//list record_id ddda onsetnumcod2a onsettxtcod2a if onsetnumcod2a==99 & onsettxtcod2a==99
replace flag36=flag36+1 if onsetnumcod2a==99 & onsettxtcod2a==99 //0 changes
//replace corr_KG=corr_KG+1 if record_id==2362|record_id==2425 //2 changes
//replace onsetnumcod2a=999 if onsetnumcod2a==99 & onsettxtcod2a==99 //7 changes


** onsettxtcod2a: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 37
** (77) missing
count if onsetnumcod2a!=. & onsetnumcod2a!=999 & onsettxtcod2a==. //0
//list record_id ddda onsetnumcod2a onsettxtcod2a if onsetnumcod2a!=. & onsetnumcod2a!=999 & onsettxtcod2a==.
//replace flag37=flag37+1 if record_id==967 //1 change
//replace corr_KG=corr_KG+1 if record_id==967 //1 change
//replace onsettxtcod2a=99 if onsetnumcod2a!=. & onsettxtcod2a==. //1 change
** (78) possibly invalid
count if onsetnumcod2a!=999 & onsettxtcod2a==99 //1 - correct
//list record_id ddda duration* onsetnumcod2a onsettxtcod2a if onsetnumcod2a!=999 & onsettxtcod2a==99
//replace flag37=flag37+1 if onsetnumcod2a!=999 & onsettxtcod2a==99 //84 changes
//replace onsetnumcod2a=999 if onsetnumcod2a!=999 & onsettxtcod2a==99 //84 changes
count if onsetnumcod2a==999 & onsettxtcod2a==99 //0
replace onsettxtcod2a=. if onsetnumcod2a==999 & onsettxtcod2a==99 //0 changes


** cod2b: Text, if missing=99: FLAG 38
** (79) missing
count if event==1 & cod2b=="" //0
//list record_id ddda cod2b if event==1 & cod2b==""
** (80) invalid
count if event==1 & regexm(cod2b, "[a-z]") //0
//list record_id ddda cod2b onsetnumcod2b onsettxtcod2b if event==1 & regexm(cod2b, "[a-z]")
replace flag38=flag38+1 if event==1 & regexm(cod2b, "[a-z]") //0 changes
//replace corr_intern=corr_intern+1 if event==1 & regexm(cod2b, "[a-z]")
replace cod2b=upper(cod2b) //0 changes
replace cod2b = rtrim(ltrim(itrim(cod2b))) //222 changes
count if event==1 & regexm(cod2b,"NIL")|event==1 & regexm(cod2b,"ND") //21 - all correct
//list record_id ddda cod2b if event==1 & regexm(cod2b,"NIL")|event==1 & regexm(cod2b,"ND")


** onsetnumcod2b: Integer - min=0, max=99, if missing=99: FLAG 39
** (81) missing
count if event==1 & cod2b!="99" & onsetnumcod2b==. //0
//list record_id ddda cod2b onsetnumcod2b onsettxtcod2b if event==1 & cod2b!="99" & onsetnumcod2b==.
** (82) possibly invalid
count if onsetnumcod2b==999 & onsettxtcod2b!=. & onsettxtcod2b!=99 //0
//list record_id ddda onsetnumcod2b onsettxtcod2b if onsetnumcod2b==999 & onsettxtcod2b!=. & onsettxtcod2b!=99
replace flag39=flag39+1 if onsetnumcod2b==999 & onsettxtcod2b!=. & onsettxtcod2b!=99 //0 changes
//replace onsetnumcod2b=99 if onsetnumcod2b==999 & onsettxtcod2b!=. & onsettxtcod2b!=99 //0 changes
count if onsetnumcod2b==99 & onsettxtcod2b==99 //0
//list record_id ddda onsetnumcod2b onsettxtcod2b if onsetnumcod2b==99 & onsettxtcod2b==99
replace flag39=flag39+1 if onsetnumcod2b==99 & onsettxtcod2b==99 //0 changes
//replace corr_KG=corr_KG+1 if record_id==2362|record_id==2425 //2 changes
replace onsetnumcod2b=999 if onsetnumcod2b==99 & onsettxtcod2b==99 //0 changes


** onsettxtcod2b: 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND": FLAG 40
** (83) missing
count if onsetnumcod2b!=. & onsetnumcod2b!=999 & onsettxtcod2b==. //0
//list record_id ddda onsetnumcod2b onsettxtcod2b if onsetnumcod2b!=. & onsetnumcod2b!=999 & onsettxtcod2b==.
** (84) possibly invalid
count if onsetnumcod2b!=999 & onsettxtcod2b==99 //1 - correct
//list record_id ddda duration* onsetnumcod2b onsettxtcod2b if onsetnumcod2b!=999 & onsettxtcod2b==99
//replace flag40=flag40+1 if onsetnumcod2b!=999 & onsettxtcod2b==99 //0 changes
//replace onsetnumcod2b=999 if onsetnumcod2b!=999 & onsettxtcod2b==99 //0 changes
//replace onsettxtcod2b=. if onsetnumcod2b!=999 & onsettxtcod2b==99 //123 changes
count if onsetnumcod2b==999 & onsettxtcod2b==99 //0
replace onsettxtcod2b=. if onsetnumcod2b==999 & onsettxtcod2b==99 //0 changes


** pod: Text, if missing=99: FLAG 41
** (85) missing
count if event==1 & pod=="" //0
//list record_id ddda pod if event==1 & pod==""
** (86) invalid
count if event==1 & regexm(pod, "[a-z]") //3
//list record_id ddda pod if event==1 & regexm(pod, "[a-z]")
replace flag41=flag41+1 if event==1 & regexm(pod, "[a-z]")
replace corr_AH=corr_AH+1 if record_id==208|record_id==324 //2 changes
replace corr_KG=corr_KG+1 if record_id==1268 //1 change
replace pod=upper(pod) //3 changes
replace pod = rtrim(ltrim(itrim(pod))) //158 changes
count if event==1 & regexm(pod,"NIL")|event==1 & regexm(pod,"ND") //279 - all correct
//list record_id ddda pod if event==1 & regexm(pod,"NIL")|event==1 & regexm(pod,"ND")


** deathparish: FLAG 42
** (87) missing
count if event==1 & deathparish==. //0
//list record_id ddda deathparish if event==1 & deathparish==.
** (88) invalid - see district demarcations noted below:
/*	Districts are assigned based on death parish
		District A - anything below top rock christ church and st. michael 
		District B - anything above top rock christ church and st. george
		District C - st. philip and st. john
		District D - st. thomas
		District E - st. james, st. peter, st. lucy
		District F - st. joseph, st. andrew
*/
** (88) Christ Church
count if deathparish==1 & district!=1 //252 - all correct
//list record_id ddda district pod deathparish if deathparish==1 & district!=1
** (89) St Andrew
count if deathparish==2 & district!=6 //1
//list record_id ddda deathparish district pod if deathparish==2 & district!=6
replace flag42=flag42+1 if record_id==2837
replace district=6 if record_id==2837
replace corr_KG=corr_KG+1 if record_id==2837
** (90) St George
count if deathparish==3 & district!=2 //1
//list record_id ddda deathparish district pod if deathparish==3 & district!=2
replace flag42=flag42+1 if record_id==2393
replace district=2 if record_id==2393
replace corr_KG=corr_KG+1 if record_id==2393
** (91) St James
count if deathparish==4 & district!=5 //0
//list record_id ddda deathparish district pod if deathparish==4 & district!=5
//replace flag42=flag42+1 if record_id==2360 // change
//replace corr_intern=corr_intern+1 if record_id==2360 // change
//replace district=5 if record_id==2360 // change
** (92) St John
count if deathparish==5 & district!=3 //1
//list record_id ddda deathparish district pod if deathparish==5 & district!=3
replace flag42=flag42+1 if record_id==742
replace deathparish=4 if record_id==742 //1 change
replace corr_KG=corr_KG+1 if record_id==742
** (93) St Joseph
count if deathparish==6 & district!=6 //0
//list record_id ddda deathparish district pod if deathparish==6 & district!=6
** (94) St Lucy
count if deathparish==7 & district!=5 //1
//list record_id ddda deathparish district pod if deathparish==7 & district!=5
replace flag42=flag42+1 if record_id==55
replace deathparish=8 if record_id==55 //1 change
replace corr_AH=corr_AH+1 if record_id==55
** (95) St Michael
count if deathparish==8 & district!=1 //1
//list record_id ddda deathparish district pod if deathparish==8 & district!=1
replace flag42=flag42+1 if record_id==2361
replace deathparish=3 if record_id==2361 //1 change
replace corr_KG=corr_KG+1 if record_id==2361
** (96) St Peter
count if deathparish==9 & district!=5 //0
//list record_id ddda deathparish district pod if deathparish==9 & district!=5
//replace flag42=flag42+1 if record_id==185|record_id==2568|record_id==4046 //3 changes
//replace corr_AH=corr_AH+1 if record_id==4046 //1 change
//replace deathparish=8 if record_id==185 //1 change
//replace district=5 if record_id==2568|record_id==4046 //2 change
** (97) St Philip
count if deathparish==10 & district!=3 //0
//list record_id ddda deathparish district pod if deathparish==10 & district!=3
//replace flag42=flag42+1 if record_id==2420|record_id==3765|record_id==4266 //3 changes
//replace corr_KG=corr_KG+1 if record_id==2420|record_id==3765 //2 changes
//replace district=3 if record_id==2420 //1 change
//replace deathparish=8 if record_id==3765|record_id==4266 //2 changes
** (98) St Thomas
count if deathparish==11 & district!=4 //0
//list record_id ddda deathparish district pod if deathparish==11 & district!=4
//replace flag42=flag42+1 if record_id==21|record_id==60|record_id==2599 //1 change
//replace corr_intern=corr_intern+1 if record_id==60|record_id==2599 //2 changes
//replace deathparish=8 if record_id==21|record_id==60
//replace district=4 if record_id==2599 //1 change


** regdate: Y-M-D: FLAG 43
** (99) missing
count if event==1 & regdate==. //0
//list record_id ddda dod regdate if event==1 & regdate==.
** (100) invalid - future date
count if event==1 & regdate!=. & regdate>today //0
sort record_id
//list record_id ddda dod regdate pname if event==1 & regdate!=. & regdate>today
//replace pname=subinstr(pname,"J","JO",.) if record_id==1789 //1 change
//replace flag43=flag43+1 if record_id==1789
//replace corr_intern=corr_intern+1 if record_id==1789
//replace regdate=regdate-365.25 if record_id==1789 //1 change
//replace flag43=flag43+1 if record_id==1789
//replace corr_intern=corr_intern+1 if record_id==1789 //1 change
drop today


** certifier: Text, if missing=99: FLAG 44
** (101) missing
count if event==1 & certifier=="" //1
//list record_id ddda certifier if event==1 & certifier==""
replace flag44=flag44+1 if event==1 & certifier=="" //1 change
replace corr_KG=corr_KG+1 if event==1 & certifier=="" //1 change
replace certifier="99" if record_id==2796
count if certifier=="999" //0
//replace flag44=flag44+1 if record_id==163 //1 change
//replace corr_AH=corr_AH+1 if record_id==163 //1 change
//replace certifier="99" if certifier=="999" //1 change
** (102) invalid
count if event==1 & regexm(certifier, "[a-z]") //1
//list record_id ddda certifier if event==1 & regexm(certifier, "[a-z]")
replace flag44=flag44+1 if event==1 & regexm(certifier, "[a-z]") //1 change
replace corr_KG=corr_KG+1 if event==1 & regexm(certifier, "[a-z]") //1 change
replace certifier=upper(certifier) //1 change
replace certifier = rtrim(ltrim(itrim(certifier))) //128 changes
count if event==1 & regexm(certifier,"NIL")|event==1 & regexm(certifier,"ND") //198 - all correct
//list record_id ddda certifier if event==1 & regexm(certifier,"NIL")|event==1 & regexm(certifier,"ND")


** certifieraddr: Text, if missing=99: FLAG 45
** (103) missing
count if event==1 & certifieraddr=="" //1
//list record_id ddda certifieraddr if event==1 & certifieraddr==""
replace flag45=flag45+1 if event==1 & certifieraddr=="" //1 change
replace corr_KG=corr_KG+1 if event==1 & certifieraddr=="" //1 change
replace certifieraddr="99" if record_id==2796
** (104) invalid
count if event==1 & regexm(certifieraddr, "[a-z]") //1
//list record_id ddda certifieraddr if event==1 & regexm(certifieraddr, "[a-z]")
replace flag45=flag45+1 if event==1 & regexm(certifieraddr, "[a-z]") //1 change
replace corr_KG=corr_KG+1 if event==1 & regexm(certifieraddr, "[a-z]") //1 change
replace certifieraddr=upper(certifieraddr) //1 change
replace certifieraddr = rtrim(ltrim(itrim(certifieraddr))) //49 changes
count if event==1 & regexm(certifieraddr,"NIL")|event==1 & regexm(certifieraddr,"ND") //69 - all correct
//list record_id ddda certifieraddr if event==1 & regexm(certifieraddr,"NIL")|event==1 & regexm(certifieraddr,"ND")


** namematch: readonly: FLAG 46
** (105) missing
count if event==1 & namematch==. //3104 - already checked for duplicates above
replace namematch=2 if event==1 & namematch==. //2574 changes
//list record_id ddda namematch if event==1 & namematch==.


** cleaned: 1=Yes; 2=No: FLAG 47
** (105) missing
count if event==1 & cleaned==. //3132
count if event==1 & cleaned==2 //0
//tab cleaned if event==1 ,m
replace cleaned=1 if event==1 & (cleaned==.|cleaned==2) //3132 changes


** death_certificate_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete: FLAG 48
** (106) missing
count if event==1 & recstatdc==. //0
** (107) invalid - incomplete and no reason given in field comment of redcapdb
count if event==1 & recstatdc==0 //1
//list record_id ddda dddoa recstatdc if event==1 & recstatdc==0
replace flag48=flag48+1 if event==1 & recstatdc==0 //1 change
replace corr_KG=corr_KG+1 if event==1 & recstatdc==0 //1 change
replace recstatdc=2 if event==1 & recstatdc==0 //1 change
** (108) invalid - unverified and no reason given in field comment of redcapdb
count if event==1 & recstatdc==1 //0


*******************
** TRACKING FORM **
*******************

** tfdddoa: Y-M-D, readonly: FLAG 49
** (109) missing
count if event==2 & tfdddoa==. //0
//list record_id tfdddoaend if event==2 & tfdddoa==.
replace tfdddoa=tfdddoaend if event==2 & tfdddoa==. //0 changes


** tfdddoatstart: H:M, readonly: FLAG 50
** (110) missing
count if event==2 & tfdddoatstart==. //0


** tfddda: readonly, user logged into redcap: FLAG 51
** (111) missing
count if event==2 & tfddda==. //0
//list record_id if event==2 & tfddda==.
//replace tfddda=4 if record_id==2315 //1 change
count if length(tfddda2)<4 & tfddda2!="" //0
//list record_id tfddda tfddda2 if length(tfddda2)<4 & tfddda2!=""
//replace tfddda2="karen.greene" if tfddda2=="kg" //1 change


** tfregnumstart: integer: FLAG 52
** (112) missing
count if event==2 & tfregnumstart==. //0
//list record_id if event==2 & tfregnumstart==.
//drop if record_id==3035 //1 deleted - blank record


** tfdistrictstart: letters only: FLAG 53
** (113) missing
count if event==2 & tfdistrictstart=="" //0
** (114) invalid
count if event==2 & regexm(tfdistrictstart, "[a-z]") //0
//replace tfdistrictstart = rtrim(ltrim(itrim(tfdistrictstart))) //0 changes


** tfregnumend: integer: FLAG 54
** (115) missing
count if event==2 & tfregnumend==. //0
//list record_id tfddda tfregnumend if event==2 & tfregnumend==.


** tfdistrictend: letters only: FLAG 55
** (116) missing
count if event==2 & tfdistrictend=="" //0
//list record_id tfddda tfdistrictend if event==2 & tfdistrictend==""
** (117) invalid
count if event==2 & regexm(tfdistrictend, "[a-z]") //0
//replace tfdistrictend = rtrim(ltrim(itrim(tfdistrictend))) //0 changes


** tfdddoaend: Y-M-D, readonly: FLAG 56
** (118) missing
count if event==2 & tfdddoaend==. //0
//list record_id tfdddoa if event==2 & tfdddoaend==.
replace tfdddoaend=tfdddoa if event==2 & tfdddoaend==. //0 changes


** tfdddoatend: H:M, readonly: FLAG 57
** (119) missing
count if event==2 & tfdddoatend==. //0
//list record_id tfddda tfdddoatstart if event==2 & tfdddoatend==.
/*
replace flag57=flag57+1 if event==2 & tfdddoatend==. //19 changes
replace corr_intern=corr_intern+1 if event==2 & tfdddoatend==. & tfddda==98 //9 changes
replace corr_AH=corr_AH+1 if event==2 & tfdddoatend==. & tfddda==25 //2 changes
replace corr_TH=corr_TH+1 if event==2 & tfdddoatend==. & tfddda==14 //4 changes
replace corr_KG=corr_KG+1 if event==2 & tfdddoatend==. & tfddda==4 //4 changes
replace tfdddoatend=tfdddoatstart if record_id==41
replace tfdddoatstart= clock("31dec1899 08:58:00", "DMYhms") if record_id==41
replace tfdddoatend=tfdddoatstart if record_id==82
replace tfdddoatstart= clock("31dec1899 09:12:00", "DMYhms") if record_id==82
replace tfdddoatend=tfdddoatstart if record_id==124
replace tfdddoatstart= clock("31dec1899 08:56:00", "DMYhms") if record_id==124
drop if record_id==165 //1 deleted - duplicate of 82
replace regnum=301 if record_id==182 //1 change
replace tfdddoatend=tfdddoatstart if record_id==210
replace tfdddoatstart= clock("31dec1899 12:13:00", "DMYhms") if record_id==210
replace tfdddoatend=tfdddoatstart if record_id==253
replace tfdddoatstart= clock("31dec1899 09:16:00", "DMYhms") if record_id==253
replace tfdddoatend=tfdddoatstart if record_id==340
replace tfdddoatstart= clock("31dec1899 10:47:00", "DMYhms") if record_id==340
replace tfdddoatend= clock("31dec1899 14:13:00", "DMYhms") if record_id==341
replace tfdddoatend=tfdddoatstart if record_id==382
replace tfdddoatstart= clock("31dec1899 09:39:00", "DMYhms") if record_id==382
replace tfdddoatend=tfdddoatstart if record_id==430
replace tfdddoatstart= clock("31dec1899 10:40:00", "DMYhms") if record_id==430
replace tfdddoatend= clock("31dec1899 10:21:00", "DMYhms") if record_id==483
replace tfdddoatend=tfdddoatstart if record_id==524
replace tfdddoatstart= clock("31dec1899 08:43:00", "DMYhms") if record_id==524
replace tfdddoatend=tfdddoatstart if record_id==568
replace tfdddoatstart= clock("31dec1899 11:03:00", "DMYhms") if record_id==568
replace tfdddoatend=tfdddoatstart if record_id==2293
replace tfdddoatstart= clock("31dec1899 09:19:00", "DMYhms") if record_id==2293
replace tfdddoatend=tfdddoatstart if record_id==2312
replace tfdddoatstart= clock("31dec1899 12:21:00", "DMYhms") if record_id==2312
replace tfdddoatend= clock("31dec1899 13:06:00", "DMYhms") if record_id==2313
replace tfdddoatend=tfdddoatstart if record_id==2314
replace tfdddoatstart= clock("31dec1899 09:26:00", "DMYhms") if record_id==2314
replace tfdddoatend=tfdddoatstart if record_id==2315
replace tfdddoatstart= clock("31dec1899 09:12:00", "DMYhms") if record_id==2315
replace tfdddoatend=tfdddoatstart if record_id==2739
replace tfdddoatstart= clock("31dec1899 12:51:00", "DMYhms") if record_id==2739
*/

** tfddelapsedh: auto-generated, readonly: FLAG 58
** (120) missing
count if tfdddoatstart!=. & tfdddoatend!=. & tfddelapsedh==. //0
//list record_id tfddda tfdddoatstart tfdddoatend if tfdddoatstart!=. & tfdddoatend!=. & tfddelapsedh==.
replace tfddelapsedh=hours(tfdddoatend-tfdddoatstart) if tfdddoatstart!=. & tfdddoatend!=. & tfddelapsedh==. //0 changes
format tfddelapsedh %9.0f


** tfddelapsedm: auto-generated, readonly: FLAG 59
** (120) missing
count if tfdddoatstart!=. & tfdddoatend!=. & tfddelapsedm==. //0
//list record_id tfddda tfdddoatstart tfdddoatend if tfdddoatstart!=. & tfdddoatend!=. & tfddelapsedm==.
replace tfddelapsedm=minutes(tfdddoatend-tfdddoatstart) if tfdddoatstart!=. & tfdddoatend!=. & tfddelapsedm==. //0 changes


** tfddtxt: FLAG 60
replace tfddtxt = rtrim(ltrim(itrim(tfddtxt))) //96 changes


** tracking_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete: FLAG 61
** (121) missing
count if event==2 & recstattf==. //0
** (122) invalid - incomplete and no reason given in field comment of redcapdb
count if event==2 & recstattf==0 //0
//list record_id tfddda tfdddoa recstattf if event==2 & recstattf==0
//replace flag61=flag61+1 if event==2 & recstattf==0 //1 change
//replace corr_KG=corr_KG+1 if event==2 & recstattf==0 //1 change
replace recstattf=2 if event==2 & recstattf==0 //0 changes
** (123) invalid - unverified and no reason given in field comment of redcapdb
count if event==2 & recstattf==1 //0


** Create electoral match variable as in multi-year REDCap death database
gen elecmatch=.
label var elecmatch "Record matched to electoral list?"
label define elecmatch_lab 1 "Yes" 2 "No" , modify
label values elecmatch elecmatch_lab

** Check for those with missing NRN and check against electoral sheet
count if event==1 & nrn=="" //112
order record_id pname address age agetxt parish sex dod

preserve
drop if nrn==""
sort nrn 
quietly by nrn : gen dupnrn = cond(_N==1,0,_n)
sort nrn record_id pname
count if dupnrn>0 //
list record_id namematch pname nrn dod sex age address if dupnrn>0, sepby(nrn)
drop dupnrn
restore

drop if record_id==365 //duplicate of record_id 1301
replace cod1b=subinstr(cod1b,"IMMOBILSATION","IMMOBILISATION",.) if record_id==1301

preserve
clear
import excel using "`datapath'\version07\2-working\MissingNRNs_mort_20220629.xlsx" , firstrow case(lower)
save "`datapath'\version07\2-working\electoral_nrn" ,replace
restore

merge 1:1 record_id using "`datapath'\version07\2-working\electoral_nrn" ,force
/*
    Result                      Number of obs
    -----------------------------------------
    Not matched                         3,204
        from master                     3,204  (_merge==1)
        from using                          0  (_merge==2)

    Matched                                25  (_merge==3)
    -----------------------------------------
*/
replace nrn=elec_nrn if _merge==3 //25 changes
replace elecmatch=elec_match if _merge==3 //25 changes
drop elec_* _merge
erase "`datapath'\version07\2-working\electoral_nrn.dta"

** JC 29jun2022: did not use below code but may use in the future
/*
preserve
** Change death variable names to differentiate with electoral list variables
rename * dd_*
save "`datapath'\version07\2-working\2021_deaths_electoral_dc" ,replace
clear

** Import electoral list
import excel using "`datapath'\version07\1-input\BNRDeathData2021_DATA_2022-04-14_0721_excel.xlsx" , firstrow case(lower)
rename * elec_*

** Add 2021 death dataset
append using "`datapath'\version07\2-working\2021_deaths_electoral_dc"


** Check for duplicates using NRN
drop if nrn==""|nrn=="999999-9999"|regexm(nrn,"9999") //remove blank/missing NRNs as these will be flagged as duplicates of each other
// deleted
sort nrn 
quietly by nrn : gen dup = cond(_N==1,0,_n)
sort nrn registrynumber lastname firstname
count if dup>0 //0

** Check for missing NRNs in death dataset and update NRN in death dataset variable using electoral list NRN
count if dd_nrnnd==2 //104 missing NRNs in death ds
count if dd_nrnnd==2 & elec_nrn!=.
record_id 2796 listed as female but has male fname and is in electoral list as male - has alot of missing info (pg 1102 of electoral list).

** Remove electoral variables and revert death variable names back to original format
drop elec_*
rename dd_* *

erase "`datapath'\version07\2-working\2021_deaths_electoral_dc.dta"
save "`datapath'\version07\2-working\2021_deaths_electoral_matched_dc" ,replace
restore
*/
//use "`datapath'\version07\2-working\2021_deaths_electoral_matched_dc" ,clear

** Incidental correction to first name
replace flag9=flag9+1 if record_id==158 // changes
replace corr_AH=corr_AH+1 if record_id==158 // changes
replace pname=subinstr(pname,"MA","A",.) if record_id==158

** REMOVE dod>2021
tab dodyear ,m //2020=3 deaths; 2021=3143 deaths
count if dodyear!=year(dod) //0
drop if event==1 & dodyear>2021 //0 deleted - already deleted above

//drop tfddda2 - don't remove as needed in 3_export_deaths.do

** ORDER variables according to position in DeathData REDCap database
order record_id redcap_event_name event dddoa ddda odda certtype regnum district pname address parish ///
	  sex age agetxt nrnnd nrn mstatus occu durationnum durationtxt dod dodyear ///
	  cod1a onsetnumcod1a onsettxtcod1a cod1b onsetnumcod1b onsettxtcod1b ///
	  cod1c onsetnumcod1c onsettxtcod1c cod1d onsetnumcod1d onsettxtcod1d ///
	  cod2a onsetnumcod2a onsettxtcod2a cod2b onsetnumcod2b onsettxtcod2b ///
	  pod deathparish regdate certifier certifieraddr namematch cleaned recstatdc ///
	  tfdddoa tfdddoatstart tfddda tfregnumstart tfdistrictstart tfregnumend tfdistrictend ///
      tfddelapsedh tfddelapsedm tfdddoaend tfdddoatend tfddtxt recstattf

count //3228; 3229; 3230; 3233; 3239; 3240; 3242; 3243; 3249

label data "BNR MORTALITY data 2021"
notes _dta :These data prepared from BB national death register & BNR (Redcap) deathdata database
save "`datapath'\version07\3-output\2021_deaths_cleaned_dqi_dc" ,replace

** Create dataset for merging with cancer death dataset in p117/version04
preserve
drop flag* corr_* tfdddoa tfdddoatstart tfddda tfregnumstart tfdistrictstart tfregnumend tfdistrictend tfddelapsedh tfddelapsedm tfdddoaend tfdddoatend tfddtxt recstattf tfddda2
drop if event!=1 //97 deleted
label data "BNR MORTALITY data 2021 for Cancer Annual Report"
notes _dta :These data prepared from BB national death register & BNR (Redcap) deathdata database
save "`datapath'\version07\3-output\2021_deaths_cleaned_cancer" ,replace
restore

** REMOVE variables and labels not needed in DeathData REDCap database
drop birthdate flag*
label drop _all

** REDCap will not import H:M:S format so had to change cfdate from %tcCCYY-NN-DD_HH:MM:SS to below format
format dddoa %tcCCYY-NN-DD_HH:MM
gen data_2021=1  //to differentiate between multi-year and single-year databases in dofile 2b_clean_all_deaths
count //3228; 3229; 3230; 3233; 3239; 3240; 3242; 3243; 3249 - JC 11jan2023 found a duplicate (2961 + 3243) but duplicate (2961) was removed from multi-yr db

label data "BNR MORTALITY data 2021"
notes _dta :These data prepared from BB national death register & BNR (Redcap) deathdata database
save "`datapath'\version07\3-output\2021_deaths_cleaned_matching_dc" ,replace

